/* AI-only notices. The local guide retains its own translations. */
const CHAT_COPY = {
  "en": [
    "Ask about Patrick, or get a project pick.",
    "AI replies use Groq. Your question and recent chat are sent there. Avoid private details. AI can be wrong.",
    "AI · GROQ",
    "Thinking…",
    "AI is unavailable. Here is a prepared answer instead."
  ],
  "sk": [
    "Opýtaj sa na Patricka alebo si nechaj odporučiť projekt.",
    "AI odpovedá cez Groq. Posiela sa tam otázka a nedávna konverzácia. Nezadávaj súkromné údaje. AI sa môže mýliť.",
    "AI · GROQ",
    "Premýšľam…",
    "AI je nedostupná. Toto je pripravená odpoveď."
  ],
  "hu": [
    "Kérdezz Patrickról, vagy kérj projektajánlót.",
    "Az AI a Groq szolgáltatást használja. A kérdésed és a legutóbbi üzenetek oda kerülnek. Ne adj meg személyes adatokat. Az AI tévedhet.",
    "AI · GROQ",
    "Gondolkodom…",
    "Az AI nem elérhető. Helyette egy előre megírt válasz következik."
  ],
  "pl": [
    "Zapytaj o Patricka albo poproś o polecenie projektu.",
    "AI korzysta z Groq. Twoje pytanie i ostatnie wiadomości są tam wysyłane. Nie podawaj prywatnych danych. AI może się mylić.",
    "AI · GROQ",
    "Myślę…",
    "AI jest niedostępna. Oto przygotowana wcześniej odpowiedź."
  ],
  "cs": [
    "Zeptej se na Patricka nebo si nech doporučit projekt.",
    "AI odpovídá přes Groq. Odesílá se tam otázka a nedávná konverzace. Nezadávej soukromé údaje. AI se může mýlit.",
    "AI · GROQ",
    "Přemýšlím…",
    "AI je nedostupná. Toto je připravená odpověď."
  ],
  "de": [
    "Frag nach Patrick oder lass dir ein Projekt empfehlen.",
    "Die KI nutzt Groq. Deine Frage und die letzten Nachrichten werden dorthin gesendet. Keine privaten Daten eingeben. Die KI kann sich irren.",
    "KI · GROQ",
    "Denke nach…",
    "Die KI ist nicht verfügbar. Hier ist stattdessen eine vorbereitete Antwort."
  ],
  "es": [
    "Pregunta por Patrick o pide una recomendación de proyecto.",
    "La IA usa Groq. Tu pregunta y los mensajes recientes se envían allí. Evita datos privados. La IA puede equivocarse.",
    "IA · GROQ",
    "Pensando…",
    "La IA no está disponible. Esta es una respuesta preparada."
  ],
  "pt": [
    "Pergunta sobre o Patrick ou pede uma recomendação de projeto.",
    "A IA usa o Groq. A tua pergunta e as mensagens recentes são enviadas para lá. Evita dados privados. A IA pode errar.",
    "IA · GROQ",
    "A pensar…",
    "A IA não está disponível. Esta é uma resposta preparada."
  ],
  "fr": [
    "Pose une question sur Patrick ou demande un projet à découvrir.",
    "L’IA utilise Groq. Ta question et les messages récents y sont envoyés. Évite les données privées. L’IA peut se tromper.",
    "IA · GROQ",
    "Réflexion…",
    "L’IA est indisponible. Voici une réponse préparée."
  ],
  "zh": [
    "了解 Patrick，或让助手推荐一个项目。",
    "AI 通过 Groq 回答。你的问题和最近的聊天内容会发送到该服务。请勿提供隐私信息。AI 可能出错。",
    "AI · GROQ",
    "思考中…",
    "AI 暂时不可用。以下是预先编写的回答。"
  ],
  "hi": [
    "Patrick के बारे में पूछें या कोई प्रोजेक्ट सुझाने को कहें।",
    "AI के जवाब Groq से आते हैं। आपका सवाल और हाल के संदेश वहाँ भेजे जाते हैं। निजी जानकारी न दें। AI गलत हो सकता है।",
    "AI · GROQ",
    "सोच रहा हूँ…",
    "AI उपलब्ध नहीं है। यह पहले से तैयार जवाब है।"
  ],
  "ar": [
    "اسأل عن Patrick أو اطلب اقتراح مشروع.",
    "يستخدم الذكاء الاصطناعي Groq. يُرسل سؤالك والرسائل الأخيرة إليه. تجنّب المعلومات الخاصة. قد يخطئ الذكاء الاصطناعي.",
    "AI · GROQ",
    "جارٍ التفكير…",
    "الذكاء الاصطناعي غير متاح. إليك إجابة معدّة مسبقًا."
  ],
  "bn": [
    "Patrick সম্পর্কে জিজ্ঞাসা করুন বা একটি প্রকল্পের পরামর্শ নিন।",
    "AI উত্তর দিতে Groq ব্যবহার করে। আপনার প্রশ্ন এবং সাম্প্রতিক বার্তা সেখানে পাঠানো হয়। ব্যক্তিগত তথ্য দেবেন না। AI ভুল করতে পারে।",
    "AI · GROQ",
    "ভাবছি…",
    "AI উপলব্ধ নেই। এটি আগে থেকে তৈরি করা উত্তর।"
  ],
  "ru": [
    "Спроси о Patrick или попроси порекомендовать проект.",
    "ИИ использует Groq. Твой вопрос и последние сообщения отправляются туда. Не вводи личные данные. ИИ может ошибаться.",
    "ИИ · GROQ",
    "Думаю…",
    "ИИ недоступен. Вот заранее подготовленный ответ."
  ],
  "ur": [
    "Patrick کے بارے میں پوچھیں یا کسی منصوبے کی تجویز مانگیں۔",
    "AI جوابات کے لیے Groq استعمال کرتا ہے۔ آپ کا سوال اور حالیہ پیغامات وہاں بھیجے جاتے ہیں۔ نجی معلومات نہ دیں۔ AI غلطی کر سکتا ہے۔",
    "AI · GROQ",
    "سوچ رہا ہوں…",
    "AI دستیاب نہیں ہے۔ یہ پہلے سے تیار کردہ جواب ہے۔"
  ],
  "id": [
    "Tanya tentang Patrick atau minta rekomendasi proyek.",
    "AI menggunakan Groq. Pertanyaan dan pesan terakhirmu dikirim ke sana. Hindari data pribadi. AI bisa salah.",
    "AI · GROQ",
    "Sedang berpikir…",
    "AI tidak tersedia. Ini jawaban yang telah disiapkan."
  ],
  "ja": [
    "Patrickについて聞くか、プロジェクトのおすすめを聞いてください。",
    "AI は Groq を利用します。質問と直近の会話が送信されます。個人情報は入力しないでください。AI は間違えることがあります。",
    "AI · GROQ",
    "考え中…",
    "AI を利用できません。代わりに用意された回答を表示します。"
  ]
};
Object.defineProperty(CHAT_COPY,'recommendations',{value:{
  en:{intro:'Here are a few projects that may fit.',heading:'A few projects that may fit',previous:'Previous project',next:'Next project',notes:'Read project notes',position:'{current} of {total}',whyTitle:'Why these?',whyText:'The picks use your question and the public titles, descriptions and project types shown here.',compareLabel:'Compare ({count}/3)',compareAria:'Compare selected projects, {count} selected',addToCompare:'Add to compare',removeFromCompare:'Remove from compare',compareTitle:'Compare projects',selectedCount:'{count} selected'},
  sk:{intro:'Tu je pár projektov, ktoré by ti mohli sadnúť.',heading:'Projekty, ktoré by ti mohli sadnúť',previous:'Predchádzajúci projekt',next:'Ďalší projekt',notes:'Pozrieť poznámky',position:'{current} z {total}',whyTitle:'Prečo tieto?',whyText:'Výber vychádza z tvojej otázky a verejných názvov, opisov a typov projektov zobrazených tu.',compareLabel:'Porovnať ({count}/3)',compareAria:'Porovnať vybrané projekty, vybrané: {count}',addToCompare:'Pridať na porovnanie',removeFromCompare:'Odobrať z porovnania',compareTitle:'Porovnanie projektov',selectedCount:'Vybrané: {count}'},
  hu:{intro:'Néhány projekt, amely érdekes lehet számodra.',heading:'Néhány neked való projekt',previous:'Előző projekt',next:'Következő projekt',notes:'Projektjegyzetek',position:'{current}/{total}',whyTitle:'Miért ezek?',whyText:'A választás a kérdésedre és az itt látható nyilvános címekre, leírásokra és projekttípusokra épül.',compareLabel:'Összehasonlítás ({count}/3)',compareAria:'Kiválasztott projektek összehasonlítása, kiválasztva: {count}',addToCompare:'Hozzáadás az összehasonlításhoz',removeFromCompare:'Eltávolítás az összehasonlításból',compareTitle:'Projektek összehasonlítása',selectedCount:'Kiválasztva: {count}'},
  pl:{intro:'Oto kilka projektów, które mogą Cię zainteresować.',heading:'Projekty, które mogą Cię zainteresować',previous:'Poprzedni projekt',next:'Następny projekt',notes:'Zobacz notatki',position:'{current} z {total}',whyTitle:'Dlaczego te?',whyText:'Wybór opiera się na Twoim pytaniu oraz widocznych tutaj publicznych nazwach, opisach i typach projektów.',compareLabel:'Porównaj ({count}/3)',compareAria:'Porównaj wybrane projekty, wybrano: {count}',addToCompare:'Dodaj do porównania',removeFromCompare:'Usuń z porównania',compareTitle:'Porównanie projektów',selectedCount:'Wybrano: {count}'},
  cs:{intro:'Tady je pár projektů, které by tě mohly zaujmout.',heading:'Projekty, které by tě mohly zaujmout',previous:'Předchozí projekt',next:'Další projekt',notes:'Zobrazit poznámky',position:'{current} z {total}',whyTitle:'Proč právě tyto?',whyText:'Výběr vychází z tvé otázky a veřejných názvů, popisů a typů projektů zobrazených zde.',compareLabel:'Porovnat ({count}/3)',compareAria:'Porovnat vybrané projekty, vybráno: {count}',addToCompare:'Přidat k porovnání',removeFromCompare:'Odebrat z porovnání',compareTitle:'Porovnání projektů',selectedCount:'Vybráno: {count}'},
  de:{intro:'Hier sind ein paar Projekte, die zu dir passen könnten.',heading:'Projekte, die zu dir passen könnten',previous:'Vorheriges Projekt',next:'Nächstes Projekt',notes:'Projektnotizen ansehen',position:'{current} von {total}',whyTitle:'Warum diese?',whyText:'Die Auswahl basiert auf deiner Frage sowie den hier sichtbaren öffentlichen Projekttiteln, Beschreibungen und Typen.',compareLabel:'Vergleichen ({count}/3)',compareAria:'Ausgewählte Projekte vergleichen, ausgewählt: {count}',addToCompare:'Zum Vergleich hinzufügen',removeFromCompare:'Aus dem Vergleich entfernen',compareTitle:'Projekte vergleichen',selectedCount:'Ausgewählt: {count}'},
  es:{intro:'Aquí tienes algunos proyectos que podrían interesarte.',heading:'Proyectos que podrían interesarte',previous:'Proyecto anterior',next:'Proyecto siguiente',notes:'Ver notas del proyecto',position:'{current} de {total}',whyTitle:'¿Por qué estos?',whyText:'La selección usa tu pregunta y los nombres, descripciones y tipos de proyecto públicos que aparecen aquí.',compareLabel:'Comparar ({count}/3)',compareAria:'Comparar proyectos seleccionados, seleccionados: {count}',addToCompare:'Añadir a la comparación',removeFromCompare:'Quitar de la comparación',compareTitle:'Comparar proyectos',selectedCount:'Seleccionados: {count}'},
  pt:{intro:'Aqui estão alguns projetos que podem interessar-te.',heading:'Projetos que podem interessar-te',previous:'Projeto anterior',next:'Projeto seguinte',notes:'Ver notas do projeto',position:'{current} de {total}',whyTitle:'Porquê estes?',whyText:'A seleção usa a tua pergunta e os nomes, descrições e tipos públicos dos projetos apresentados aqui.',compareLabel:'Comparar ({count}/3)',compareAria:'Comparar projetos selecionados, selecionados: {count}',addToCompare:'Adicionar à comparação',removeFromCompare:'Remover da comparação',compareTitle:'Comparar projetos',selectedCount:'Selecionados: {count}'},
  fr:{intro:'Voici quelques projets qui pourraient t’intéresser.',heading:'Des projets qui pourraient t’intéresser',previous:'Projet précédent',next:'Projet suivant',notes:'Lire les notes du projet',position:'{current} sur {total}',whyTitle:'Pourquoi ceux-ci ?',whyText:'La sélection tient compte de ta question et des noms, descriptions et types de projets publics affichés ici.',compareLabel:'Comparer ({count}/3)',compareAria:'Comparer les projets sélectionnés, sélectionnés : {count}',addToCompare:'Ajouter à la comparaison',removeFromCompare:'Retirer de la comparaison',compareTitle:'Comparer les projets',selectedCount:'Sélectionnés : {count}'},
  zh:{intro:'这里有几个可能适合你的项目。',heading:'你可能感兴趣的项目',previous:'上一个项目',next:'下一个项目',notes:'查看项目说明',position:'第 {current} 个，共 {total} 个',whyTitle:'为什么推荐这些？',whyText:'推荐依据是你的问题，以及此处显示的公开项目名称、描述和类型。',compareLabel:'比较 ({count}/3)',compareAria:'比较已选项目，已选 {count} 个',addToCompare:'加入比较',removeFromCompare:'从比较中移除',compareTitle:'项目比较',selectedCount:'已选 {count} 个'},
  hi:{intro:'ये कुछ प्रोजेक्ट आपके काम के हो सकते हैं।',heading:'आपकी रुचि के कुछ प्रोजेक्ट',previous:'पिछला प्रोजेक्ट',next:'अगला प्रोजेक्ट',notes:'प्रोजेक्ट की जानकारी देखें',position:'{total} में से {current}',whyTitle:'ये प्रोजेक्ट क्यों?',whyText:'चयन आपके सवाल और यहाँ दिखाए गए सार्वजनिक प्रोजेक्ट नाम, विवरण और प्रकार पर आधारित है।',compareLabel:'तुलना करें ({count}/3)',compareAria:'चुने गए प्रोजेक्ट की तुलना करें, चुने गए: {count}',addToCompare:'तुलना में जोड़ें',removeFromCompare:'तुलना से हटाएँ',compareTitle:'प्रोजेक्ट की तुलना',selectedCount:'चुने गए: {count}'},
  ar:{intro:'إليك بعض المشاريع التي قد تناسبك.',heading:'مشاريع قد تهمك',previous:'المشروع السابق',next:'المشروع التالي',notes:'اقرأ تفاصيل المشروع',position:'{current} من {total}',whyTitle:'لماذا هذه المشاريع؟',whyText:'يعتمد الاختيار على سؤالك وأسماء المشاريع العامة وأوصافها وأنواعها الظاهرة هنا.',compareLabel:'قارن ({count}/3)',compareAria:'قارن المشاريع المحددة، المحدد: {count}',addToCompare:'أضف إلى المقارنة',removeFromCompare:'أزل من المقارنة',compareTitle:'مقارنة المشاريع',selectedCount:'المحدد: {count}'},
  bn:{intro:'এখানে কয়েকটি প্রকল্প আছে যা আপনার কাজে লাগতে পারে।',heading:'আপনার আগ্রহের কিছু প্রকল্প',previous:'আগের প্রকল্প',next:'পরের প্রকল্প',notes:'প্রকল্পের নোট দেখুন',position:'{total}টির মধ্যে {current}',whyTitle:'এগুলো কেন?',whyText:'নির্বাচনটি আপনার প্রশ্ন এবং এখানে দেখা যায় এমন প্রকল্পের প্রকাশ্য নাম, বিবরণ ও ধরন ব্যবহার করে।',compareLabel:'তুলনা করুন ({count}/3)',compareAria:'নির্বাচিত প্রকল্প তুলনা করুন, নির্বাচিত: {count}',addToCompare:'তুলনায় যোগ করুন',removeFromCompare:'তুলনা থেকে সরান',compareTitle:'প্রকল্প তুলনা',selectedCount:'নির্বাচিত: {count}'},
  ru:{intro:'Вот несколько проектов, которые могут тебе подойти.',heading:'Проекты, которые могут тебя заинтересовать',previous:'Предыдущий проект',next:'Следующий проект',notes:'О проекте',position:'{current} из {total}',whyTitle:'Почему эти?',whyText:'Выбор основан на твоём вопросе и открытых названиях, описаниях и типах проектов, показанных здесь.',compareLabel:'Сравнить ({count}/3)',compareAria:'Сравнить выбранные проекты, выбрано: {count}',addToCompare:'Добавить к сравнению',removeFromCompare:'Убрать из сравнения',compareTitle:'Сравнение проектов',selectedCount:'Выбрано: {count}'},
  ur:{intro:'یہ چند منصوبے آپ کی دلچسپی کے ہو سکتے ہیں۔',heading:'آپ کی دلچسپی کے چند منصوبے',previous:'پچھلا منصوبہ',next:'اگلا منصوبہ',notes:'منصوبے کی تفصیل دیکھیں',position:'{total} میں سے {current}',whyTitle:'یہی کیوں؟',whyText:'انتخاب آپ کے سوال اور یہاں دکھائے گئے عوامی منصوبوں کے نام، تفصیل اور اقسام پر مبنی ہے۔',compareLabel:'موازنہ کریں ({count}/3)',compareAria:'منتخب منصوبوں کا موازنہ کریں، منتخب: {count}',addToCompare:'موازنے میں شامل کریں',removeFromCompare:'موازنے سے ہٹائیں',compareTitle:'منصوبوں کا موازنہ',selectedCount:'منتخب: {count}'},
  id:{intro:'Berikut beberapa proyek yang mungkin cocok untukmu.',heading:'Beberapa proyek yang mungkin cocok untukmu',previous:'Proyek sebelumnya',next:'Proyek berikutnya',notes:'Lihat catatan proyek',position:'{current} dari {total}',whyTitle:'Kenapa ini?',whyText:'Pilihan ini memakai pertanyaanmu serta nama, deskripsi, dan jenis proyek publik yang terlihat di sini.',compareLabel:'Bandingkan ({count}/3)',compareAria:'Bandingkan proyek yang dipilih, dipilih: {count}',addToCompare:'Tambahkan untuk dibandingkan',removeFromCompare:'Hapus dari perbandingan',compareTitle:'Bandingkan proyek',selectedCount:'Dipilih: {count}'},
  ja:{intro:'興味に合いそうなプロジェクトをいくつか紹介します。',heading:'興味に合いそうなプロジェクト',previous:'前のプロジェクト',next:'次のプロジェクト',notes:'プロジェクトの説明を見る',position:'全 {total} 件中 {current} 件目',whyTitle:'このプロジェクトを選んだ理由',whyText:'質問と、ここに表示されている公開プロジェクトの名前、説明、種類をもとに選んでいます。',compareLabel:'比較 ({count}/3)',compareAria:'選択したプロジェクトを比較、選択数: {count}',addToCompare:'比較に追加',removeFromCompare:'比較から削除',compareTitle:'プロジェクトを比較',selectedCount:'選択中: {count}'}
}});
Object.defineProperty(CHAT_COPY,'offline',{value:{
 en:['When AI is available, your question and recent chat go to Groq. Otherwise, prepared answers are used. Avoid private details; chat clears on reload.','AI WHEN AVAILABLE · PREPARED FALLBACK'],
 sk:['Keď je AI dostupná, otázka a nedávna konverzácia sa odošlú do Groq. Inak sa použijú pripravené odpovede. Nezadávaj súkromné údaje. Chat sa po obnovení vymaže.','AI PODĽA DOSTUPNOSTI · PRIPRAVENÉ ODPOVEDE'],
 hu:['Ha elérhető az AI, a kérdésed és a legutóbbi beszélgetés a Groqhoz kerül. Egyébként előre elkészített válaszokat kapsz. Ne adj meg személyes adatokat; frissítéskor a beszélgetés törlődik.','AI, HA ELÉRHETŐ · ELŐKÉSZÍTETT VÁLASZOK'],
 pl:['Gdy AI jest dostępne, pytanie i ostatnia rozmowa trafiają do Groq. W przeciwnym razie używane są gotowe odpowiedzi. Nie podawaj prywatnych danych. Rozmowa znika po odświeżeniu.','AI, GDY DOSTĘPNE · GOTOWE ODPOWIEDZI'],
 cs:['Když je AI dostupná, otázka a nedávný chat se odešlou do Groq. Jinak se použijí připravené odpovědi. Nezadávej soukromé údaje. Chat po obnovení zmizí.','AI PODLE DOSTUPNOSTI · PŘIPRAVENÉ ODPOVĚDI'],
 de:['Wenn KI verfügbar ist, werden deine Frage und der letzte Chat an Groq gesendet. Sonst gibt es vorbereitete Antworten. Keine privaten Daten eingeben; beim Neuladen wird der Chat gelöscht.','KI WENN VERFÜGBAR · VORBEREITETE ANTWORTEN'],
 es:['Si la IA está disponible, tu pregunta y el chat reciente se envían a Groq. Si no, se usan respuestas preparadas. Evita datos privados; el chat se borra al recargar.','IA SI ESTÁ DISPONIBLE · RESPUESTAS PREPARADAS'],
 pt:['Quando a IA está disponível, a pergunta e a conversa recente são enviadas para o Groq. Caso contrário, são usadas respostas preparadas. Evita dados privados; a conversa desaparece ao recarregar.','IA QUANDO DISPONÍVEL · RESPOSTAS PREPARADAS'],
 fr:['Quand l’IA est disponible, ta question et les échanges récents sont envoyés à Groq. Sinon, des réponses préparées sont utilisées. Évite les données privées ; le chat disparaît au rechargement.','IA SI DISPONIBLE · RÉPONSES PRÉPARÉES'],
 zh:['AI 可用时，你的问题和最近的对话会发送至 Groq；否则使用预设回答。请勿提供隐私信息；刷新页面后对话会清除。','AI 可用时 · 预设回答'],
 hi:['AI उपलब्ध होने पर आपका सवाल और हाल की बातचीत Groq को भेजी जाती है। अन्यथा तैयार जवाब मिलते हैं। निजी जानकारी न दें; पेज रीफ़्रेश करने पर चैट मिट जाती है।','AI उपलब्ध होने पर · तैयार जवाब'],
 ar:['عند توفر الذكاء الاصطناعي، يُرسل سؤالك وآخر المحادثة إلى Groq. وإلا فستُستخدم إجابات مُعدة مسبقًا. تجنب المعلومات الخاصة؛ تُحذف المحادثة عند إعادة التحميل.','الذكاء الاصطناعي عند توفره · إجابات مُعدة'],
 bn:['AI পাওয়া গেলে আপনার প্রশ্ন ও সাম্প্রতিক কথোপকথন Groq-এ পাঠানো হবে। না হলে প্রস্তুত উত্তর ব্যবহার করা হবে। ব্যক্তিগত তথ্য দেবেন না; পৃষ্ঠা রিফ্রেশ হলে চ্যাট মুছে যাবে।','AI থাকলে · প্রস্তুত উত্তর'],
 ru:['Когда доступен ИИ, вопрос и недавняя переписка отправляются в Groq. Иначе используются готовые ответы. Не указывайте личные данные; после перезагрузки чат очищается.','ИИ ПРИ НАЛИЧИИ · ГОТОВЫЕ ОТВЕТЫ'],
 ur:['AI دستیاب ہو تو آپ کا سوال اور حالیہ گفتگو Groq کو بھیجی جاتی ہے۔ ورنہ تیار جوابات استعمال ہوتے ہیں۔ نجی معلومات نہ دیں؛ صفحہ دوبارہ کھلنے پر چیٹ مٹ جاتی ہے۔','AI دستیاب ہو تو · تیار جوابات'],
 id:['Saat AI tersedia, pertanyaan dan percakapan terbaru dikirim ke Groq. Jika tidak, jawaban yang sudah disiapkan akan digunakan. Hindari data pribadi; chat dihapus saat halaman dimuat ulang.','AI JIKA TERSEDIA · JAWABAN SIAP PAKAI'],
 ja:['AIが利用できる場合、質問と直近の会話がGroqに送信されます。利用できない場合は用意された回答を使います。個人情報は入力しないでください。再読み込みで会話は消去されます。','AI利用時 · 用意された回答']
}});
Object.defineProperty(CHAT_COPY,'assistant',{value:{
 en:{searchLabel:'Find a project',searchPlaceholder:'Name, topic, or technology…',searchEmpty:'No matching projects',pathLaunch:'Explore AI, agents & RL',pathTitle:'A short guided tour',pathQuestion:'What would you like to understand?',pathBack:'Back',pathSubjects:['AI agents','RAG & retrieval','Reinforcement learning'],pathAngles:[['How tool use fits','How evaluation works'],['Finding useful sources','Grounding an answer'],['Rewards and feedback','PPO in practice']],compareRows:['Stage & tech','What it does','Try or inspect'],compareProject:'Project',compareHint:'Based on details shown on each project card.',compareExplain:'Ask AI to explain the differences',compareFallback:'The comparison above uses each project’s stage, tools, description and public link.',pathFallback:['An agent pairs a model with tools and a loop: read, choose, act, check. Trialkeep is the published project here focused on evaluating agent decisions.','RAG retrieves useful source text before a model answers. Feedcairn collects official feeds, but its published app is not a RAG answer system.','Reinforcement learning improves a policy through reward feedback. Patrick’s thesis combined PPO agents with LLM-generated maps for a multiplayer game.']},
 sk:{searchLabel:'Nájsť projekt',searchPlaceholder:'Názov, téma alebo technológia…',searchEmpty:'Nenašli sa žiadne projekty',pathLaunch:'Preskúmať AI agentov a RL',pathTitle:'Krátky sprievodca',pathQuestion:'Čomu chceš porozumieť?',pathBack:'Späť',pathSubjects:['AI agenti','RAG a vyhľadávanie','Reinforcement learning'],pathAngles:[['Ako funguje práca s nástrojmi','Ako sa hodnotí výsledok'],['Ako nájsť zdroje','Ako oprieť odpoveď o zdroje'],['Odmeny a spätná väzba','PPO v praxi']],compareRows:['Fáza a technológie','Čo projekt robí','Vyskúšať alebo preskúmať'],compareProject:'Projekt',compareHint:'Priame porovnanie faktov uvedených na kartách projektov.',compareExplain:'Vysvetliť rozdiely pomocou AI',compareFallback:'Vyššie porovnávame fázu, technológie, opis a verejný odkaz každého projektu.',pathFallback:['Agent spája model s nástrojmi a cyklom: prečítať, vybrať, konať, overiť. Trialkeep je tu zverejnený projekt zameraný na hodnotenie rozhodnutí agentov.','RAG najprv vyhľadá užitočný text v zdrojoch a až potom z neho model tvorí odpoveď. Feedcairn zbiera oficiálne feedy, ale jeho zverejnená aplikácia nie je RAG systém na odpovede.','Reinforcement learning zlepšuje stratégiu pomocou odmien a spätnej väzby. Patrickova diplomovka spojila PPO agentov s mapami generovanými LLM pre multiplayerovú hru.']},
 hu:{searchLabel:'Projekt keresése',searchPlaceholder:'Név, téma vagy technológia…',searchEmpty:'Nincs találat',pathLaunch:'AI-ágensek és RL felfedezése',pathTitle:'Rövid kalauz',pathQuestion:'Mit szeretnél megérteni?',pathBack:'Vissza',pathSubjects:['AI-ágensek','RAG és keresés','Megerősítéses tanulás'],pathAngles:[['Eszközhasználat','Értékelés'],['Hasznos források megtalálása','Forrásokra épülő válasz'],['Jutalom és visszajelzés','PPO a gyakorlatban']],compareRows:['Állapot és technológia','Mit csinál?','Kipróbálás vagy megtekintés'],compareProject:'Projekt',compareHint:'Összehasonlítás a projektkártyákon látható tények alapján.',compareExplain:'Különbségek magyarázata AI-val',compareFallback:'A fenti összehasonlítás a projekt állapotát, technológiáit, leírását és nyilvános hivatkozását használja.',pathFallback:['Az ágens eszközökkel és egy ciklussal egészíti ki a modellt: olvas, választ, cselekszik, ellenőriz. A Trialkeep itt az ágensdöntések értékelésével foglalkozó közzétett projekt.','A RAG előbb hasznos forrásszöveget keres, majd a modell abból válaszol. A Feedcairn hivatalos feedeket gyűjt, de a nyilvános alkalmazása nem RAG-válaszrendszer.','A megerősítéses tanulás jutalom-visszajelzéssel javítja a szabályzatot. Patrick diplomamunkája PPO-ágenseket és LLM-mel generált pályákat kapcsolt egy többszereplős játékban.']},
 pl:{searchLabel:'Znajdź projekt',searchPlaceholder:'Nazwa, temat lub technologia…',searchEmpty:'Brak pasujących projektów',pathLaunch:'Poznaj AI, agentów i RL',pathTitle:'Krótki przewodnik',pathQuestion:'Co chcesz zrozumieć?',pathBack:'Wstecz',pathSubjects:['Agenci AI','RAG i wyszukiwanie','Uczenie przez wzmacnianie'],pathAngles:[['Jak działają narzędzia','Jak oceniać wyniki'],['Znajdowanie źródeł','Odpowiedź oparta na źródłach'],['Nagrody i informacja zwrotna','PPO w praktyce']],compareRows:['Etap i technologie','Co robi projekt','Wypróbuj lub sprawdź'],compareProject:'Projekt',compareHint:'Porównanie korzysta z faktów widocznych na kartach projektów.',compareExplain:'Poproś AI o wyjaśnienie różnic',compareFallback:'Powyższe porównanie obejmuje etap, technologie, opis i publiczny link każdego projektu.',pathFallback:['Agent łączy model z narzędziami i pętlą: czyta, wybiera, działa, sprawdza. Trialkeep to opublikowany tu projekt poświęcony ocenie decyzji agentów.','RAG najpierw wyszukuje przydatne fragmenty źródeł, a potem model odpowiada na ich podstawie. Feedcairn zbiera oficjalne kanały, ale jego publiczna aplikacja nie jest systemem odpowiedzi RAG.','Uczenie przez wzmacnianie poprawia politykę działania na podstawie nagród. Praca magisterska Patricka łączyła agentów PPO z mapami generowanymi przez LLM do gry wieloosobowej.']},
 cs:{searchLabel:'Najít projekt',searchPlaceholder:'Název, téma nebo technologie…',searchEmpty:'Žádné odpovídající projekty',pathLaunch:'Prozkoumat AI, agenty a RL',pathTitle:'Krátký průvodce',pathQuestion:'Čemu chceš porozumět?',pathBack:'Zpět',pathSubjects:['AI agenti','RAG a vyhledávání','Reinforcement learning'],pathAngles:[['Jak funguje práce s nástroji','Jak hodnotit výsledky'],['Hledání užitečných zdrojů','Odpověď podložená zdroji'],['Odměny a zpětná vazba','PPO v praxi']],compareRows:['Fáze a technologie','Co projekt dělá','Vyzkoušet nebo prohlédnout'],compareProject:'Projekt',compareHint:'Přímé srovnání faktů uvedených na kartách projektů.',compareExplain:'Vysvětlit rozdíly pomocí AI',compareFallback:'Srovnání výše používá fázi, technologie, popis a veřejný odkaz každého projektu.',pathFallback:['Agent propojuje model s nástroji a cyklem: přečíst, vybrat, jednat, ověřit. Trialkeep je zdejší zveřejněný projekt zaměřený na hodnocení rozhodnutí agentů.','RAG nejprve vyhledá užitečný text ve zdrojích a pak z něj model sestaví odpověď. Feedcairn sbírá oficiální feedy, jeho zveřejněná aplikace ale není systém pro RAG odpovědi.','Reinforcement learning zlepšuje strategii pomocí odměn a zpětné vazby. Patrickova diplomová práce spojila PPO agenty s mapami generovanými pomocí LLM pro multiplayerovou hru.']},
 de:{searchLabel:'Projekt finden',searchPlaceholder:'Name, Thema oder Technologie…',searchEmpty:'Keine passenden Projekte',pathLaunch:'KI, Agenten und RL entdecken',pathTitle:'Ein kurzer Rundgang',pathQuestion:'Was möchtest du verstehen?',pathBack:'Zurück',pathSubjects:['KI-Agenten','RAG und Suche','Bestärkendes Lernen'],pathAngles:[['Wie Werkzeuge ins Spiel kommen','Wie Ergebnisse bewertet werden'],['Nützliche Quellen finden','Antworten auf Quellen stützen'],['Belohnung und Feedback','PPO in der Praxis']],compareRows:['Status und Technik','Was es tut','Ausprobieren oder ansehen'],compareProject:'Projekt',compareHint:'Der Vergleich nutzt die Angaben auf den jeweiligen Projektkarten.',compareExplain:'KI soll die Unterschiede erklären',compareFallback:'Verglichen werden Status, Technik, Beschreibung und öffentlicher Link jedes Projekts.',pathFallback:['Ein Agent verbindet ein Modell mit Werkzeugen und einem Ablauf: lesen, wählen, handeln, prüfen. Trialkeep ist hier das veröffentlichte Projekt zur Bewertung von Agentenentscheidungen.','RAG sucht zuerst relevante Quelltexte, bevor ein Modell daraus antwortet. Feedcairn sammelt offizielle Feeds, ist in seiner veröffentlichten Form aber kein RAG-Antwortsystem.','Bestärkendes Lernen verbessert eine Strategie durch Belohnungsfeedback. Patricks Masterarbeit verband PPO-Agenten mit LLM-generierten Karten für ein Multiplayer-Spiel.']},
 es:{searchLabel:'Buscar proyecto',searchPlaceholder:'Nombre, tema o tecnología…',searchEmpty:'No hay proyectos coincidentes',pathLaunch:'Explorar IA, agentes y RL',pathTitle:'Guía rápida',pathQuestion:'¿Qué quieres entender?',pathBack:'Atrás',pathSubjects:['Agentes de IA','RAG y recuperación','Aprendizaje por refuerzo'],pathAngles:[['Cómo se usan las herramientas','Cómo evaluar resultados'],['Encontrar fuentes útiles','Responder con fuentes'],['Recompensas y feedback','PPO en la práctica']],compareRows:['Estado y tecnología','Qué hace','Probar o consultar'],compareProject:'Proyecto',compareHint:'Comparación basada en los datos visibles de cada tarjeta.',compareExplain:'Pedir a la IA que explique las diferencias',compareFallback:'La comparación anterior usa el estado, la tecnología, la descripción y el enlace público de cada proyecto.',pathFallback:['Un agente combina un modelo con herramientas y un ciclo: leer, elegir, actuar y comprobar. Trialkeep es el proyecto publicado aquí que evalúa decisiones de agentes.','RAG busca primero texto útil en las fuentes y después el modelo responde a partir de él. Feedcairn recopila feeds oficiales, pero su aplicación pública no es un sistema de respuestas RAG.','El aprendizaje por refuerzo mejora una política mediante recompensas. La tesis de Patrick combinó agentes PPO con mapas generados por LLM para un juego multijugador.']},
 pt:{searchLabel:'Encontrar um projeto',searchPlaceholder:'Nome, tema ou tecnologia…',searchEmpty:'Nenhum projeto encontrado',pathLaunch:'Explorar IA, agentes e RL',pathTitle:'Visita guiada rápida',pathQuestion:'O que gostarias de perceber?',pathBack:'Voltar',pathSubjects:['Agentes de IA','RAG e pesquisa','Aprendizagem por reforço'],pathAngles:[['Como entram as ferramentas','Como avaliar resultados'],['Encontrar fontes úteis','Responder com fontes'],['Recompensas e feedback','PPO na prática']],compareRows:['Estado e tecnologia','O que faz','Experimentar ou consultar'],compareProject:'Projeto',compareHint:'Comparação baseada no que está indicado em cada cartão.',compareExplain:'Pedir à IA que explique as diferenças',compareFallback:'A comparação acima usa o estado, as tecnologias, a descrição e o link público de cada projeto.',pathFallback:['Um agente combina um modelo com ferramentas e um ciclo: ler, escolher, agir, verificar. Trialkeep é o projeto publicado aqui dedicado a avaliar decisões de agentes.','RAG procura primeiro texto útil nas fontes e só depois o modelo responde com base nele. Feedcairn recolhe feeds oficiais, mas a aplicação publicada não é um sistema de respostas RAG.','A aprendizagem por reforço melhora uma política com feedback de recompensas. A tese de Patrick combinou agentes PPO com mapas gerados por LLM para um jogo multijogador.']},
 fr:{searchLabel:'Trouver un projet',searchPlaceholder:'Nom, thème ou technologie…',searchEmpty:'Aucun projet correspondant',pathLaunch:'Explorer l’IA, les agents et le RL',pathTitle:'Petit parcours guidé',pathQuestion:'Que veux-tu comprendre ?',pathBack:'Retour',pathSubjects:['Agents IA','RAG et recherche','Apprentissage par renforcement'],pathAngles:[['Le rôle des outils','Évaluer les résultats'],['Trouver les bonnes sources','Ancrer une réponse'],['Récompenses et retours','PPO en pratique']],compareRows:['Statut et technologies','Ce que fait le projet','Essayer ou consulter'],compareProject:'Projet',compareHint:'La comparaison reprend les informations visibles sur chaque carte.',compareExplain:'Demander à l’IA d’expliquer les différences',compareFallback:'La comparaison ci-dessus utilise le statut, les technologies, le résumé et le lien public de chaque projet.',pathFallback:['Un agent associe un modèle à des outils et une boucle : lire, choisir, agir, vérifier. Trialkeep est le projet publié ici consacré à l’évaluation des décisions d’agents.','Le RAG recherche d’abord des extraits utiles, puis le modèle répond à partir de ces sources. Feedcairn collecte des flux officiels, mais son application publiée n’est pas un système de réponses RAG.','L’apprentissage par renforcement améliore une politique grâce aux récompenses. Le mémoire de Patrick associait des agents PPO à des cartes générées par LLM pour un jeu multijoueur.']},
 zh:{searchLabel:'查找项目',searchPlaceholder:'名称、主题或技术…',searchEmpty:'没有匹配的项目',pathLaunch:'了解 AI、智能体与强化学习',pathTitle:'快速引导',pathQuestion:'你想了解什么？',pathBack:'返回',pathSubjects:['AI 智能体','RAG 与检索','强化学习'],pathAngles:[['工具如何参与','如何评估结果'],['查找有用来源','基于来源回答'],['奖励与反馈','PPO 实践']],compareRows:['阶段与技术','项目功能','试用或查看'],compareProject:'项目',compareHint:'对比仅使用各项目卡片上展示的信息。',compareExplain:'让 AI 解释差异',compareFallback:'上方按项目阶段、技术、简介和公开链接进行对比。',pathFallback:['智能体将模型、工具和循环结合起来：读取、选择、执行、检查。Trialkeep 是这里公开的、专注评估智能体决策的项目。','RAG 会先检索有用的来源文本，再让模型据此回答。Feedcairn 收集官方信息流，但其公开应用不是 RAG 问答系统。','强化学习通过奖励反馈改进策略。Patrick 的硕士论文将 PPO 智能体与 LLM 生成的多人游戏地图结合起来。']},
 hi:{searchLabel:'प्रोजेक्ट खोजें',searchPlaceholder:'नाम, विषय या तकनीक…',searchEmpty:'कोई मेल खाता प्रोजेक्ट नहीं',pathLaunch:'AI, एजेंट और RL जानें',pathTitle:'छोटी मार्गदर्शित यात्रा',pathQuestion:'आप क्या समझना चाहते हैं?',pathBack:'वापस',pathSubjects:['AI एजेंट','RAG और खोज','रीइन्फोर्समेंट लर्निंग'],pathAngles:[['टूल कैसे काम आते हैं','नतीजों का मूल्यांकन'],['उपयोगी स्रोत ढूँढना','स्रोतों पर आधारित उत्तर'],['इनाम और प्रतिक्रिया','व्यवहार में PPO']],compareRows:['स्थिति और तकनीक','यह क्या करता है','आज़माएँ या देखें'],compareProject:'प्रोजेक्ट',compareHint:'तुलना में हर प्रोजेक्ट कार्ड पर दिखे तथ्य ही हैं।',compareExplain:'AI से अंतर समझें',compareFallback:'ऊपर की तुलना हर प्रोजेक्ट की स्थिति, तकनीक, विवरण और सार्वजनिक लिंक पर आधारित है।',pathFallback:['एजेंट मॉडल को टूल और एक चक्र से जोड़ता है: पढ़ना, चुनना, करना, जाँचना। Trialkeep यहाँ प्रकाशित एजेंट निर्णयों के मूल्यांकन वाला प्रोजेक्ट है।','RAG पहले स्रोतों से उपयोगी पाठ खोजता है, फिर मॉडल उसी आधार पर जवाब देता है। Feedcairn आधिकारिक फ़ीड एकत्र करता है, लेकिन उसका प्रकाशित ऐप RAG उत्तर प्रणाली नहीं है।','रीइन्फोर्समेंट लर्निंग इनाम की प्रतिक्रिया से नीति बेहतर करती है। Patrick की थीसिस में PPO एजेंट और LLM से बने मल्टीप्लेयर गेम मैप शामिल थे।']},
 ar:{searchLabel:'ابحث عن مشروع',searchPlaceholder:'الاسم أو الموضوع أو التقنية…',searchEmpty:'لا توجد مشاريع مطابقة',pathLaunch:'استكشف الذكاء الاصطناعي والوكلاء وRL',pathTitle:'جولة إرشادية قصيرة',pathQuestion:'ما الذي تريد فهمه؟',pathBack:'رجوع',pathSubjects:['وكلاء الذكاء الاصطناعي','RAG والاسترجاع','التعلّم المعزّز'],pathAngles:[['دور الأدوات','تقييم النتائج'],['العثور على المصادر','إجابة تستند إلى مصادر'],['المكافآت والتغذية الراجعة','PPO عملياً']],compareRows:['الحالة والتقنيات','ما الذي يفعله','جرّب أو استعرض'],compareProject:'المشروع',compareHint:'تعتمد المقارنة على المعلومات الظاهرة في بطاقة كل مشروع.',compareExplain:'اطلب من AI شرح الفروق',compareFallback:'تستخدم المقارنة أعلاه حالة كل مشروع وتقنياته ووصفه ورابطه العام.',pathFallback:['يجمع الوكيل بين النموذج والأدوات ودورة عمل: يقرأ، يختار، ينفّذ، ويتحقق. Trialkeep هو المشروع المنشور هنا لتقييم قرارات الوكلاء.','يسترجع RAG نصوصاً مفيدة من المصادر قبل أن يجيب النموذج بالاستناد إليها. يجمع Feedcairn الخلاصات الرسمية، لكن تطبيقه المنشور ليس نظام إجابات RAG.','يحسّن التعلّم المعزّز السياسة عبر مكافآت وتغذية راجعة. جمعت أطروحة Patrick بين وكلاء PPO وخرائط أنشأها LLM للعبة متعددة اللاعبين.']},
 bn:{searchLabel:'প্রকল্প খুঁজুন',searchPlaceholder:'নাম, বিষয় বা প্রযুক্তি…',searchEmpty:'মিল থাকা প্রকল্প নেই',pathLaunch:'AI, এজেন্ট ও RL ঘুরে দেখুন',pathTitle:'ছোট্ট গাইডেড ট্যুর',pathQuestion:'আপনি কী বুঝতে চান?',pathBack:'পেছনে',pathSubjects:['AI এজেন্ট','RAG ও রিট্রিভাল','রিইনফোর্সমেন্ট লার্নিং'],pathAngles:[['টুল কীভাবে যুক্ত হয়','ফলাফল মূল্যায়ন'],['প্রয়োজনীয় উৎস খোঁজা','উৎসভিত্তিক উত্তর'],['পুরস্কার ও প্রতিক্রিয়া','বাস্তবে PPO']],compareRows:['অবস্থা ও প্রযুক্তি','প্রকল্পটি কী করে','চেষ্টা বা পর্যালোচনা'],compareProject:'প্রকল্প',compareHint:'প্রতিটি প্রকল্প কার্ডে দেখা তথ্য দিয়েই তুলনা করা হয়েছে।',compareExplain:'AI-কে পার্থক্য ব্যাখ্যা করতে বলুন',compareFallback:'উপরের তুলনায় প্রতিটি প্রকল্পের অবস্থা, প্রযুক্তি, বর্ণনা ও প্রকাশ্য লিংক ব্যবহার করা হয়েছে।',pathFallback:['একটি এজেন্ট মডেল, টুল ও একটি চক্র মিলিয়ে কাজ করে: পড়া, বেছে নেওয়া, কাজ করা, যাচাই করা। Trialkeep এখানে প্রকাশিত এজেন্ট সিদ্ধান্ত মূল্যায়নের প্রকল্প।','RAG আগে উৎস থেকে দরকারি লেখা খুঁজে, তারপর মডেল সেটির ভিত্তিতে উত্তর দেয়। Feedcairn সরকারি ফিড সংগ্রহ করে, তবে প্রকাশিত অ্যাপটি RAG উত্তর-ব্যবস্থা নয়।','রিইনফোর্সমেন্ট লার্নিং পুরস্কারের প্রতিক্রিয়ায় নীতিকে উন্নত করে। Patrick-এর থিসিসে PPO এজেন্ট ও LLM-তৈরি মাল্টিপ্লেয়ার গেমের মানচিত্র ছিল।']},
 ru:{searchLabel:'Найти проект',searchPlaceholder:'Название, тема или технология…',searchEmpty:'Совпадений нет',pathLaunch:'Разобраться в ИИ, агентах и RL',pathTitle:'Короткий маршрут',pathQuestion:'Что хочешь понять?',pathBack:'Назад',pathSubjects:['ИИ-агенты','RAG и поиск','Обучение с подкреплением'],pathAngles:[['Роль инструментов','Оценка результатов'],['Поиск полезных источников','Ответ с опорой на источники'],['Награды и обратная связь','PPO на практике']],compareRows:['Статус и технологии','Что делает проект','Открыть или изучить'],compareProject:'Проект',compareHint:'Сравнение основано на фактах с карточек проектов.',compareExplain:'Попросить ИИ объяснить различия',compareFallback:'В сравнении выше использованы статус, технологии, описание и публичная ссылка каждого проекта.',pathFallback:['Агент объединяет модель с инструментами и циклом: прочитать, выбрать, действовать, проверить. Trialkeep — опубликованный здесь проект для оценки решений агентов.','RAG сначала находит полезные фрагменты источников, а затем модель отвечает на их основе. Feedcairn собирает официальные ленты, но его опубликованное приложение не является системой ответов RAG.','Обучение с подкреплением улучшает политику через обратную связь по награде. В дипломе Patrick совместил PPO-агентов с картами для многопользовательской игры, созданными LLM.']},
 ur:{searchLabel:'پروجیکٹ تلاش کریں',searchPlaceholder:'نام، موضوع یا ٹیکنالوجی…',searchEmpty:'کوئی متعلقہ پروجیکٹ نہیں',pathLaunch:'AI، ایجنٹس اور RL دریافت کریں',pathTitle:'مختصر رہنمائی',pathQuestion:'آپ کیا سمجھنا چاہتے ہیں؟',pathBack:'واپس',pathSubjects:['AI ایجنٹس','RAG اور بازیافت','ری انفورسمنٹ لرننگ'],pathAngles:[['ٹولز کا کردار','نتائج کی جانچ'],['مفید ذرائع تلاش کرنا','ذرائع پر مبنی جواب'],['انعام اور فیڈبیک','عملی PPO']],compareRows:['مرحلہ اور ٹیکنالوجی','یہ کیا کرتا ہے','آزمائیں یا دیکھیں'],compareProject:'پروجیکٹ',compareHint:'موازنہ ہر پروجیکٹ کارڈ پر دکھائی گئی معلومات پر مبنی ہے۔',compareExplain:'AI سے فرق سمجھنے کو کہیں',compareFallback:'اوپر ہر پروجیکٹ کا مرحلہ، ٹیکنالوجی، تفصیل اور عوامی لنک موازنہ میں شامل ہے۔',pathFallback:['ایجنٹ ماڈل کو ٹولز اور ایک چکر سے جوڑتا ہے: پڑھنا، چننا، عمل کرنا، جانچنا۔ Trialkeep یہاں ایجنٹ فیصلوں کی جانچ کا شائع شدہ پروجیکٹ ہے۔','RAG پہلے ذرائع سے مفید متن تلاش کرتا ہے، پھر ماڈل اسی بنیاد پر جواب دیتا ہے۔ Feedcairn سرکاری فیڈز جمع کرتا ہے، مگر اس کی شائع شدہ ایپ RAG جوابی نظام نہیں۔','ری انفورسمنٹ لرننگ انعامی فیڈبیک سے پالیسی بہتر کرتی ہے۔ Patrick کے تھیسس نے PPO ایجنٹس کو LLM سے بنے ملٹی پلیئر گیم کے نقشوں کے ساتھ ملایا۔']},
 id:{searchLabel:'Cari proyek',searchPlaceholder:'Nama, topik, atau teknologi…',searchEmpty:'Tidak ada proyek yang cocok',pathLaunch:'Jelajahi AI, agen, dan RL',pathTitle:'Tur panduan singkat',pathQuestion:'Apa yang ingin kamu pahami?',pathBack:'Kembali',pathSubjects:['Agen AI','RAG dan pencarian','Reinforcement learning'],pathAngles:[['Peran penggunaan alat','Cara mengevaluasi'],['Menemukan sumber berguna','Jawaban berbasis sumber'],['Imbalan dan umpan balik','PPO dalam praktik']],compareRows:['Status dan teknologi','Fungsinya','Coba atau lihat'],compareProject:'Proyek',compareHint:'Perbandingan memakai fakta yang terlihat di setiap kartu proyek.',compareExplain:'Minta AI menjelaskan perbedaannya',compareFallback:'Perbandingan di atas memakai status, teknologi, deskripsi, dan tautan publik tiap proyek.',pathFallback:['Agen menggabungkan model, alat, dan siklus: membaca, memilih, bertindak, memeriksa. Trialkeep adalah proyek publik di sini yang berfokus mengevaluasi keputusan agen.','RAG mencari teks sumber yang berguna sebelum model menjawab berdasarkan teks itu. Feedcairn mengumpulkan feed resmi, tetapi aplikasi publiknya bukan sistem jawaban RAG.','Reinforcement learning memperbaiki kebijakan melalui umpan balik imbalan. Tesis Patrick menggabungkan agen PPO dengan peta game multipemain yang dibuat LLM.']},
 ja:{searchLabel:'プロジェクトを探す',searchPlaceholder:'名前、テーマ、技術…',searchEmpty:'一致するプロジェクトはありません',pathLaunch:'AI・エージェント・RLを知る',pathTitle:'短いガイドツアー',pathQuestion:'何を知りたいですか？',pathBack:'戻る',pathSubjects:['AIエージェント','RAGと検索','強化学習'],pathAngles:[['ツールの使い方','評価の方法'],['役立つ情報源を探す','根拠のある回答'],['報酬とフィードバック','PPOの実例']],compareRows:['状態と技術','内容','試す・見る'],compareProject:'プロジェクト',compareHint:'各プロジェクトカードに表示された事実を使って比較します。',compareExplain:'AIに違いを説明してもらう',compareFallback:'上の比較では各プロジェクトの状態、技術、説明、公開リンクを使っています。',pathFallback:['エージェントはモデル、ツール、ループを組み合わせます。読む、選ぶ、実行する、確認する。Trialkeepはエージェントの判断評価を扱う公開プロジェクトです。','RAGはモデルが答える前に有用なソース文書を検索します。Feedcairnは公式フィードを集約しますが、公開アプリはRAG回答システムではありません。','強化学習は報酬のフィードバックで方策を改善します。Patrickの修士論文ではPPOエージェントとLLM生成のマルチプレイヤー用マップを組み合わせました。']}
}});
if(typeof module!=="undefined")module.exports=CHAT_COPY;
