/* An explicit contact form, separate from the guide's questions and transcript. */
(()=>{
const deliveryEnabled=true; // Recipient activated; provider accepted the publication test.
const copy={
en:['Email Patrick','Your email','Message','Send email','Your email and message go through FormSubmit to ptr.obrtal@gmail.com. Chat history is not included.','Sending…','Submitted to the email service. Inbox delivery is not confirmed.','Could not confirm submission. Your draft is still here. You can email Patrick directly.','Use a valid email and a message of 10–3,000 characters.','Open email app'],
sk:['Napísať Patrickovi','Tvoj email','Správa','Odoslať email','Tvoj email a správu odošle FormSubmit na ptr.obrtal@gmail.com. História chatu sa neposiela.','Odosielam…','Odoslané emailovej službe. Doručenie do schránky nie je potvrdené.','Odoslanie sa nepodarilo potvrdiť. Koncept zostal tu. Patrickovi môžeš napísať priamo.','Zadaj platný email a správu s 10 až 3 000 znakmi.','Otvoriť emailovú aplikáciu'],
hu:['Írj Patricknak','E-mail-címed','Üzenet','E-mail küldése','Az e-mail-címedet és üzenetedet a FormSubmit továbbítja a ptr.obrtal@gmail.com címre. A beszélgetés előzményeit nem küldjük el.','Küldés…','Elküldve az e-mail-szolgáltatónak. A kézbesítés még nincs megerősítve.','A küldést nem sikerült megerősíteni. A piszkozat megmaradt. Közvetlenül is írhatsz Patricknak.','Adj meg érvényes e-mail-címet és 10–3000 karakteres üzenetet.','Levelező megnyitása'],
pl:['Napisz do Patricka','Twój e-mail','Wiadomość','Wyślij e-mail','Twój adres i wiadomość trafią przez FormSubmit na ptr.obrtal@gmail.com. Historia czatu nie jest wysyłana.','Wysyłanie…','Przekazano usłudze pocztowej. Dostarczenie do skrzynki nie jest potwierdzone.','Nie udało się potwierdzić wysłania. Szkic pozostał tutaj. Możesz napisać bezpośrednio do Patricka.','Podaj poprawny e-mail i wiadomość o długości 10–3000 znaków.','Otwórz pocztę'],
cs:['Napsat Patrickovi','Tvůj email','Zpráva','Odeslat email','Tvůj email a zprávu odešle FormSubmit na ptr.obrtal@gmail.com. Historie chatu se neposílá.','Odesílám…','Odesláno emailové službě. Doručení do schránky není potvrzené.','Odeslání se nepodařilo potvrdit. Koncept zůstal zde. Patrickovi můžeš napsat přímo.','Zadej platný email a zprávu s 10 až 3 000 znaky.','Otevřít emailovou aplikaci'],
de:['Patrick schreiben','Deine E-Mail','Nachricht','E-Mail senden','Deine E-Mail-Adresse und Nachricht werden über FormSubmit an ptr.obrtal@gmail.com gesendet. Der Chatverlauf wird nicht mitgesendet.','Wird gesendet…','An den E-Mail-Dienst übermittelt. Die Zustellung im Postfach ist nicht bestätigt.','Der Versand konnte nicht bestätigt werden. Dein Entwurf bleibt erhalten. Du kannst Patrick direkt schreiben.','Gib eine gültige E-Mail-Adresse und 10–3.000 Zeichen ein.','E-Mail-App öffnen']};
const pending={en:'Email delivery is awaiting activation. Please use the email-app link for now.',sk:'Odosielanie čaká na aktiváciu. Zatiaľ použi odkaz na emailovú aplikáciu.',hu:'Az e-mail-küldés aktiválásra vár. Egyelőre használd a levelezőre mutató hivatkozást.',pl:'Wysyłanie czeka na aktywację. Na razie użyj odnośnika do poczty.',cs:'Odesílání čeká na aktivaci. Zatím použij odkaz na emailovou aplikaci.',de:'Der E-Mail-Versand wartet auf die Aktivierung. Nutze vorerst den Link zur E-Mail-App.'};
Object.keys(copy).forEach(k=>copy[k].push(pending[k]));
const language=document.querySelector('#guide-language'),dialog=document.querySelector('#guide-dialog');
const details=document.createElement('details');details.className='guide-contact';
details.innerHTML='<summary></summary><form><label for="contact-email"></label><input id="contact-email" name="email" type="email" autocomplete="email" maxlength="254" required><label for="contact-message"></label><textarea id="contact-message" name="message" rows="4" minlength="10" maxlength="3000" required></textarea><div class="contact-trap" aria-hidden="true"><label for="contact-website">Leave blank</label><input id="contact-website" name="website" tabindex="-1" autocomplete="off"></div><p class="contact-notice"></p><button type="submit"></button> <a href="mailto:ptr.obrtal@gmail.com"></a><p class="contact-status" role="status" aria-live="polite"></p></form>';
dialog.querySelector('#guide-form').before(details);
const form=details.querySelector('form'),button=form.querySelector('button'),status=form.querySelector('.contact-status');let busy=false,statusKey=deliveryEnabled?null:10;button.disabled=!deliveryEnabled;
const strings=()=>copy[language.value]||copy.en;
function translate(){const t=strings();details.querySelector('summary').textContent=t[0];form.querySelector('[for="contact-email"]').textContent=t[1];form.querySelector('[for="contact-message"]').textContent=t[2];button.textContent=t[busy?5:3];form.querySelector('.contact-notice').textContent=t[4];form.querySelector('a').textContent=t[9];status.textContent=statusKey===null?'':t[statusKey];}
language.addEventListener('change',translate);translate();
form.addEventListener('submit',async event=>{event.preventDefault();if(!deliveryEnabled||busy||!form.reportValidity())return;const data=Object.fromEntries(new FormData(form));try{KhonsuContact.payload(data);}catch{statusKey=8;translate();return;}busy=true;button.disabled=true;form.setAttribute('aria-busy','true');statusKey=5;translate();try{await KhonsuContact.send(data);statusKey=6;/* Retain the draft until the visitor chooses to change it. */}catch(error){statusKey=error.message==='activation'?10:7;}finally{busy=false;button.disabled=false;form.removeAttribute('aria-busy');translate();}});
})();
