/* A local, rule-based portfolio guide. No model, network calls or chat storage. */
(function () {
  const normalize = text => text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/ł/g,'l').replace(/ß/g,'ss').replace(/[\u064b-\u065f\u0670\u0640]/g,'').replace(/[^\p{L}\p{M}\p{N}+ ]/gu, ' ').replace(/\s+/g, ' ').trim();
  const topics = [
    {id:'work', keys:['what do you do','co robis','cim sa zivis','l2','support','integration','integrations','integracie','integracii','luigi','lbx','praca','praci','pracujes','work','job','audit'], en:'Patrick works as a Customer Support Partner L2 at Luigi’s Box. He investigates browser behaviour, APIs, product feeds and analytics, audits integrations, verifies fixes, and prepares engineering handovers. Luigi’s Box builds search and product discovery for e-commerce.', sk:'Patrick pracuje ako Customer Support Partner L2 v Luigi’s Box. Rieši správanie webu, API, produktové feedy a analytiku, robí audity integrácií, overuje opravy a pripravuje podklady pre vývojárov. Luigi’s Box tvorí vyhľadávanie a odporúčanie produktov pre e-shopy.', section:'about'},
    {"id": "spotify", "keys": ["spotify", "rotation", "playlist", "hudba", "music", "mood", "nalada"], "en": "A local Python script builds a private rotation from favourites and recent listening, without recurring AI calls. On request, it also searches by mood, activity or artist and favours familiar artists in the results. Mood matching is approximate, not audio analysis. The playlist is saved privately and checked after writing. This is a personal tool running on Patrick’s Mac. The source is not published.", "sk": "Lokálny Python skript skladá súkromnú rotáciu z obľúbených a nedávno počúvaných skladieb, bez pravidelných AI volaní. Na požiadanie vyhľadá hudbu podľa nálady, aktivity alebo interpreta a vo výsledkoch uprednostní známych interpretov. Nálada je približná, nejde o analýzu zvuku. Playlist uloží súkromne a overí jeho obsah. Je to osobný nástroj na Patrickovom Macu. Zdrojový kód nie je zverejnený.", "project": "rotation"},
    {id:'dots', keys:['dots','spring','react'], en:"Originally built with React and Spring Boot in 2023. The browser edition reuses the original React screens and dot images, with local game logic. Five levels, a power-up shop and guest play. No login or shared leaderboard. Play the browser edition online or explore the original source.", sk:"Pôvodne vytvorená v roku 2023 v Reacte a Spring Boote. Browser verzia používa pôvodné React obrazovky a obrázky bodiek, herná logika beží lokálne. Päť úrovní, obchod s bonusmi a hranie bez účtu. Bez prihlásenia a spoločného rebríčka. Browser verziu si môžeš zahrať online alebo si pozrieť pôvodný kód.", project:'dots'},
    {id:'bot', keys:['bot','cslys','discord bot','music bot'], en:'CSLYS is an earlier JavaScript Discord bot with music playback. The repository is historical, so current Discord and music-service compatibility is not guaranteed.', sk:'CSLYS je starší JavaScript Discord bot s prehrávaním hudby. Repozitár je historický, takže kompatibilita s dnešnými API nie je overená.', project:'bot'},
    {id:'cpp', keys:['c++','cpp','ipc','process','processes','proces','procesy'], en:'C++ and Counter-Strike got Patrick into programming. For a code example, there’s also his university team project on inter-process communication.', sk:'K programovaniu sa Patrick dostal cez C++ a Counter-Strike. Ukážkou kódu je aj univerzitný tímový projekt medziprocesovej komunikácie.', project:'ipc'},
    {id:'openai', keys:['openai','tibo','codex','fan','fandi','fandis','thsottiaux'], en:'He follows Tibo closely for the pace of his work at OpenAI and how he talks about what they’re building. This is a personal interest, not an affiliation.', sk:'Momentálne sleduje najmä Tiba. Páči sa mu tempo jeho práce v OpenAI a spôsob, akým hovorí o tom, čo tvoria. Ide o osobný záujem, nie pracovné prepojenie.', section:'now'},
    {id:'study', keys:['university','degree','thesis','tuke','ppo','reinforcement','school','skola','studium','diplomovka','diplomov','vzdelanie'], en:'Patrick has a master’s in Computer Science from TUKE. His thesis combined PPO reinforcement-learning agents and LLM-driven map generation for a multiplayer game.', sk:'Patrick má magisterské vzdelanie v informatike z TUKE. V diplomovej práci spojil PPO reinforcement-learning agentov s generovaním máp pomocou LLM pre multiplayerovú hru.', section:'now'},
    {id:'projects', keys:['projects','project','projekty','projekt','built','builds','portfolio'], en:'Start with Spotify rotation for a current personal experiment, Dots for React and Java, CSLYS for a Discord bot, or inter-process communication for C++. Most public repositories are older.', sk:'Pozri Spotify rotation ako aktuálny osobný experiment, Dots pre React a Javu, CSLYS pre Discord bota alebo medziprocesovú komunikáciu pre C++. Väčšina verejných repozitárov je staršia.', section:'projects'},
    {id:'contact', keys:['contact','kontakt','email','hire','hiring','reach','discord','github','twitter','linkedin'], en:'You can find Patrick on GitHub as khons-hu, on X as @ptr1337_, and on Discord as khons.hu. I can show you those links, but I can’t send a message or speak for him.', sk:'Patrick je na GitHube ako khons-hu, na X ako @ptr1337_ a na Discorde ako khons.hu. Ukážem ti odkazy, ale nemôžem poslať správu ani hovoriť v jeho mene.', section:'contact'},
    {id:'about', keys:['kto si','povedz mi o sebe','who are you','about','who','patrick','khonsu','yourself','kto','tebe','zacal','zaciatky','started','background','name','nickname','handle','moon knight','moonknight','meno','prezyvka','nev','nazwa','pseudonim','jmeno'], en:'Patrick Obrtal, online as khonsu. He started using the name around 2022, inspired by Moon Knight. He started with C++ and Counter-Strike, studied Computer Science at TUKE, and now works as a Customer Support Partner L2 at Luigi’s Box. He also experiments with coding agents.', sk:'Patrick Obrtal, online khonsu. Meno používa približne od roku 2022, inšpirované Moon Knightom. Začal s C++ a Counter-Strike, vyštudoval informatiku na TUKE a dnes pracuje ako Customer Support Partner L2 v Luigi’s Box. Skúša coding agentov.', section:'about'},
    {id:'ai', keys:['agi','rsi','agents','agent','ai','models','modely','llm'], en:'He follows AGI, recursive self-improvement, and new model releases, and tries coding agents in his own work. His interest in learning systems also appears in his PPO thesis project.', sk:'Sleduje AGI, rekurzívne sebazlepšovanie a nové modely. Coding agentov skúša vo vlastnej práci. Learning systémom sa venoval aj v diplomovke s PPO.', section:'now'},
    {id:'games', keys:['cs2','counter strike','games','gaming','hry','hras','hrava'], en:'Counter-Strike is part of his programming background. These days he is working on his own tools and game prototypes.', sk:'Counter-Strike patrí k jeho programátorským začiatkom. Dnes pracuje na vlastných nástrojoch a herných prototypoch.', section:'about'}
  ];
  const localeData=typeof module!=='undefined'&&module.exports?require('./language-data.js'):{EXTRA_LOCALE_PACKS,languageDirection,directionalText};
  const locales={...(typeof module!=='undefined'&&module.exports?require('./guide-locales.js'):GUIDE_LOCALES)};
  const extraKeys={work:['mit dolgozol','mivel foglalkozol','munka','dolgozik','prace','pracujesz','pracuji','co delas','prace','arbeit','beruf','was machst du','integracio','integracje'],spotify:['zene','lejatszasi lista','muzyka','hudba','musik'],cpp:['folyamatok','procesami','prozesse'],study:['egyetem','diploma','tanult','wyksztalcenie','studia','uczelni','vzdelani','diplomova','abschluss','studium','universitat'],projects:['projektek','projekteken','projektjeid','projektjei','projektet','projektach','projektami','jakimi projektami','projektow','projektech','projekten','projekte','zbudowal'],contact:['kapcsolat','elerhetoseg','elerni','skontaktowac','zatrudnic','erreichen','kontaktovat'],about:['ki vagy','kicsoda','magadrol','kim jestes','o sobie','wer bist du','uber dich','kdo jsi','o sobe'],ai:['mesterseges intelligencia','modellek','sztuczna inteligencja','modelle','kunstliche intelligenz'],games:['jatekok','jatszol','gry','grasz','hrajes','spiele','spielst']};
  topics.forEach((topic,index)=>{topic.keys.push(...(extraKeys[topic.id]||[]));Object.keys(locales).forEach(lang=>topic[lang]=locales[lang].answers[index]);});
  topics.push({"id": "calculator", "keys": ["arduino", "calculator", "kalkulack", "szamologep", "kalkulator", "taschenrechner", "calculadora"], "section": "projects", "en": "Built with a team at TUKE using an Arduino Uno, a keypad and an LCD. It evaluates arithmetic expressions with brackets and keeps calculation history.", "sk": "Tímový projekt na TUKE s Arduino Uno, klávesnicou a LCD. Vyhodnocuje aritmetické výrazy so zátvorkami a uchováva históriu výpočtov.", "hu": "A TUKE-n csapatban készült, Arduino Uno, billentyűzet és LCD használatával. Zárójeles számtani kifejezéseket értékel ki, és megőrzi a számítások előzményeit.", "pl": "Projekt zespołowy na TUKE z Arduino Uno, klawiaturą i LCD. Oblicza wyrażenia arytmetyczne z nawiasami i zachowuje historię obliczeń.", "de": "Im Team an der TUKE mit Arduino Uno, Tastenfeld und LCD gebaut. Wertet arithmetische Ausdrücke mit Klammern aus und speichert den Rechenverlauf.", "es": "Creado en equipo en TUKE con Arduino Uno, teclado y LCD. Evalúa expresiones aritméticas con paréntesis y guarda el historial de cálculos.", "cs": "Týmový projekt na TUKE s Arduino Uno, klávesnicí a LCD. Vyhodnocuje aritmetické výrazy se závorkami a uchovává historii výpočtů."});
  topics.push(...[{"id": "site", "keys": ["this site", "this website", "portfolio site", "terminal", "theme", "themes", "tento web", "weboldal", "strona", "diese website"], "project": "portfolio", "en": "This portfolio uses HTML, CSS and JavaScript, with terminal navigation, light and dark themes, and a local guide in multiple languages. Updates deploy from GitHub to Vercel.", "sk": "Toto portfólio používa HTML, CSS a JavaScript. Má terminál, svetlú a tmavú tému a lokálneho sprievodcu v viacerých jazykoch. Zmeny sa publikujú z GitHubu na Vercel.", "hu": "Ez a portfólió HTML-t, CSS-t és JavaScriptet használ. Terminált, világos és sötét témát, valamint többnyelvű helyi útmutatót tartalmaz. A frissítések GitHubról kerülnek a Vercelre.", "pl": "To portfolio używa HTML, CSS i JavaScript. Ma terminal, jasny i ciemny motyw oraz lokalny przewodnik w wielu językach. Aktualizacje trafiają z GitHuba na Vercel.", "cs": "Toto portfolio používá HTML, CSS a JavaScript. Má terminál, světlé a tmavé téma a místního průvodce v více jazycích. Změny se publikují z GitHubu na Vercel.", "de": "Dieses Portfolio nutzt HTML, CSS und JavaScript, mit Terminal, hellem und dunklem Design und einem lokalen Guide in mehreren Sprachen. Updates werden von GitHub auf Vercel veröffentlicht."}, {"id": "discovery", "keys": ["discovery", "routines", "autofollow", "weekly workflows", "rotation stuff", "automatizacie", "automatizace", "automatyzacja"], "project": "discovery", "en": "Discovery routines are weekly workflows for X recommendations and up to three relevant GitHub follows. They review candidates with an AI agent. The first scheduled run has not yet been verified.", "sk": "Discovery routines sú týždenné workflowy pre odporúčania účtov na X a sledovanie najviac troch relevantných vývojárov na GitHube. Kandidátov posudzuje AI agent. Prvý naplánovaný beh ešte nebol overený.", "hu": "A Discovery routines heti munkafolyamatokat jelent X-fiókok ajánlására és legfeljebb három releváns GitHub-fejlesztő követésére. A jelölteket AI-ágens értékeli. Az első ütemezett futás még nincs ellenőrizve.", "pl": "Discovery routines to cotygodniowe rekomendacje kont na X i obserwowanie maksymalnie trzech odpowiednich programistów na GitHubie. Kandydatów ocenia agent AI. Pierwszy zaplanowany przebieg nie został jeszcze zweryfikowany.", "cs": "Discovery routines jsou týdenní workflowy pro doporučení účtů na X a sledování nejvýše tří relevantních vývojářů na GitHubu. Kandidáty posuzuje AI agent. První naplánovaný běh ještě nebyl ověřen.", "de": "Discovery routines empfehlen wöchentlich X-Konten und folgen bis zu drei passenden GitHub-Entwicklern. Ein KI-Agent prüft die Kandidaten. Der erste geplante Durchlauf wurde noch nicht verifiziert."}]);
  Object.entries({"en": "Current projects include this portfolio and Discovery routines. ", "sk": "Aktuálne projekty zahŕňajú toto portfólio a Discovery routines. ", "hu": "A jelenlegi projektek közé tartozik ez a portfólió és a Discovery routines. ", "pl": "Aktualne projekty obejmują to portfolio i Discovery routines. ", "cs": "Aktuální projekty zahrnují toto portfolio a Discovery routines. ", "de": "Zu den aktuellen Projekten gehören dieses Portfolio und Discovery routines. "}).forEach(([lang,text])=>{topics.find(t=>t.id==='projects')[lang]=text+topics.find(t=>t.id==='projects')[lang];});
  topics.push({"id": "thinkroom", "keys": ["khonsolve", "thinkroom", "practice", "leetcode", "hackerrank", "puzzles"], "project": "thinkroom", "en": "Khonsolve is a free practice workshop with 15 original exercises in coding, debugging, logic, prompts and agent skills. It has local JavaScript, TypeScript and Python checks, gradual hints, self-review and saved drafts. The source is public on GitHub.", "sk": "Khonsolve je bezplatná dielňa s 15 pôvodnými úlohami na kódovanie, debugging, logiku, prompty a agent skills. Má lokálne JavaScript, TypeScript a Python testy, postupné nápovedy, vlastné hodnotenie a uložené poznámky. Zdrojový kód je verejný na GitHube.", "hu": "A Khonsolve ingyenes gyakorlóműhely 15 saját feladattal: kódolás, hibakeresés, logika, promptok és agent skillek. Helyi JavaScript-, TypeScript- és Python-teszteket, fokozatos segítséget, önértékelést és mentett jegyzeteket kínál. A forráskód nyilvános a GitHubon.", "pl": "Khonsolve to bezpłatny warsztat z 15 autorskimi zadaniami z programowania, debugowania, logiki, promptów i agent skills. Ma lokalne testy JavaScript, TypeScript i Python, stopniowe podpowiedzi, samoocenę i zapisane notatki. Kod jest publiczny na GitHubie.", "cs": "Khonsolve je bezplatná dílna s 15 původními úlohami na programování, debugging, logiku, prompty a agent skills. Má místní JavaScript, TypeScript a Python testy, postupné nápovědy, vlastní hodnocení a uložené poznámky. Kód je veřejný na GitHubu.", "de": "Khonsolve ist eine kostenlose Übungswerkstatt mit 15 eigenen Aufgaben zu Programmierung, Debugging, Logik, Prompts und Agent Skills. Sie bietet lokale JavaScript-, TypeScript- und Python-Tests, schrittweise Hinweise, Selbstbewertung und gespeicherte Notizen. Der Quellcode ist auf GitHub öffentlich."});
  Object.assign(topics.find(t=>t.id==='contact'),{"en": "You can email Patrick using “Email Patrick” below. It sends only the contact form through FormSubmit, not this conversation. You can also find him on GitHub, X and Discord.", "sk": "Patrickovi môžeš napísať cez „Napísať Patrickovi“ nižšie. Cez FormSubmit sa odošle iba kontaktný formulár, nie tento rozhovor. Nájdeš ho aj na GitHube, X a Discorde.", "hu": "Az alábbi „Írj Patricknak” űrlappal küldhetsz üzenetet. A FormSubmit csak az űrlapot továbbítja, ezt a beszélgetést nem.", "pl": "Możesz wysłać wiadomość przez formularz „Napisz do Patricka” poniżej. FormSubmit przesyła tylko formularz, nie tę rozmowę.", "cs": "Patrickovi můžeš napsat přes „Napsat Patrickovi“ níže. FormSubmit odešle pouze formulář, ne tento rozhovor.", "de": "Du kannst unten über „Patrick schreiben“ eine Nachricht senden. FormSubmit übermittelt nur das Formular, nicht dieses Gespräch."});
  topics.push({"id": "signal", "keys": ["khonrelay", "khonodds", "quiet signal", "rss", "ai news", "market watch", "polymarket"], "section": "projects", "en": "Khonrelay collects official AI news, releases and status feeds with RSS export. Khonodds is a read-only Polymarket research app with wallet watchlists and open-page trade alerts. These apps are live on Vercel. Khonodds loads live data. An optional daily digest runs on the server. Register each device separately. Web Push was tested in Brave on macOS. Phone delivery has not been tested.", "sk": "Khonrelay zbiera oficiálne AI novinky, vydania a stav služieb s RSS exportom. Khonodds slúži na čítanie dát Polymarketu, sledovanie peňaženiek a upozornenia na obchody pri otvorenej stránke. Tieto appky sú dostupné na Verceli. Khonodds načítava živé dáta. Voliteľný denný prehľad beží na serveri. Každé zariadenie treba pripojiť samostatne. Web Push je otestovaný v Brave na macOS. Doručenie na telefónoch zatiaľ nie.", "hu": "A Khonrelay hivatalos AI-híreket, kiadásokat és szolgáltatásállapotokat gyűjt RSS-exporttal. A Khonodds Polymarket-kutatásra szolgál, tárcalistákkal és nyitott oldalon működő kereskedési értesítésekkel. Ezek az alkalmazások elérhetők a Vercelen. A Khonodds élő adatokat tölt be. Az opcionális napi összefoglaló a szerveren fut. Minden eszközt külön kell csatlakoztatni. A Web Push macOS-en, Brave-ben tesztelve. Telefonos kézbesítés még nincs tesztelve.", "pl": "Khonrelay zbiera oficjalne wiadomości AI, wydania i status usług z eksportem RSS. Khonodds służy do analizy Polymarket, obserwowania portfeli i alertów przy otwartej stronie. Te aplikacje są dostępne na Vercelu. Khonodds pobiera dane na żywo. Opcjonalne codzienne podsumowanie działa na serwerze. Każde urządzenie wymaga osobnej rejestracji. Web Push przetestowano w Brave na macOS. Dostarczenia na telefony jeszcze nie testowano.", "cs": "Khonrelay sbírá oficiální AI novinky, vydání a stav služeb s RSS exportem. Khonodds slouží ke čtení dat Polymarketu, sledování peněženek a upozornění při otevřené stránce. Tyto aplikace jsou dostupné na Vercelu. Khonodds načítá živá data. Volitelný denní přehled běží na serveru. Každé zařízení je třeba připojit zvlášť. Web Push je otestovaný v Brave na macOS. Doručení na telefonech zatím ne.", "de": "Khonrelay sammelt offizielle KI-Nachrichten, Releases und Statusmeldungen mit RSS-Export. Khonodds bietet Polymarket-Recherche, Wallet-Beobachtungslisten und Handelshinweise bei geöffneter Seite. Diese Apps sind auf Vercel verfügbar. Khonodds lädt Live-Daten. Eine optionale tägliche Zusammenfassung läuft auf dem Server. Jedes Gerät muss einzeln verbunden werden. Web Push wurde in Brave unter macOS getestet. Die Zustellung auf Handys wurde noch nicht getestet."});
  topics.push({"id": "steam", "keys": ["khonstash", "steam shelf", "steam market", "skins", "steam item", "hourboost"], "section": "projects", "en": "Khonstash is a Steam item watchlist with manual EUR price checks, fee estimates, local notes and backup export. Target notices appear after a check. It does not trade, boost hours or monitor prices when closed.", "sk": "Khonstash je watchlist Steam itemov s manuálnou kontrolou cien v EUR, odhadom poplatkov, lokálnymi poznámkami a exportom zálohy. Upozornenie na cieľovú cenu sa zobrazí po kontrole. Appka neobchoduje, nenafukuje odohrané hodiny a nesleduje ceny po zatvorení.", "hu": "A Khonstash Steam-tárgyak figyelőlistája, kézi EUR-árellenőrzéssel, díjbecsléssel, helyi jegyzetekkel és biztonsági mentéssel. A célárjelzés ellenőrzés után jelenik meg. Nem kereskedik, nem növeli mesterségesen a játékidőt, és bezárva nem figyeli az árakat.", "pl": "Khonstash to lista obserwowanych przedmiotów Steam z ręcznym sprawdzaniem cen w EUR, szacunkiem opłat, lokalnymi notatkami i kopią zapasową. Alert ceny docelowej pojawia się po sprawdzeniu. Aplikacja nie handluje, nie nabija godzin i nie śledzi cen po zamknięciu.", "cs": "Khonstash je seznam sledovaných Steam předmětů s ruční kontrolou cen v EUR, odhadem poplatků, místními poznámkami a exportem zálohy. Upozornění na cílovou cenu se zobrazí po kontrole. Aplikace neobchoduje, nenavyšuje odehrané hodiny a nesleduje ceny po zavření.", "de": "Khonstash ist eine Merkliste für Steam-Gegenstände mit manuellen EUR-Preisabfragen, Gebührenschätzung, lokalen Notizen und Sicherungsexport. Zielpreishinweise erscheinen nach einer Abfrage. Die App handelt nicht, erhöht keine Spielstunden und überwacht keine Preise im Hintergrund."});
  Object.entries({"en": "Khonsolve · Khonrelay · Khonodds. Khonrelay collects official AI news, releases and status feeds with RSS export. Khonodds is a read-only Polymarket research app with wallet watchlists and open-page trade alerts. These apps are live on Vercel. Khonodds loads live data. An optional daily digest runs on the server. Register each device separately. Web Push was tested in Brave on macOS. Phone delivery has not been tested.", "sk": "Khonsolve · Khonrelay · Khonodds. Khonrelay zbiera oficiálne AI novinky, vydania a stav služieb s RSS exportom. Khonodds slúži na čítanie dát Polymarketu, sledovanie peňaženiek a upozornenia na obchody pri otvorenej stránke. Tieto appky sú dostupné na Verceli. Khonodds načítava živé dáta. Voliteľný denný prehľad beží na serveri. Každé zariadenie treba pripojiť samostatne. Web Push je otestovaný v Brave na macOS. Doručenie na telefónoch zatiaľ nie.", "hu": "Khonsolve · Khonrelay · Khonodds. A Khonrelay hivatalos AI-híreket, kiadásokat és szolgáltatásállapotokat gyűjt RSS-exporttal. A Khonodds Polymarket-kutatásra szolgál, tárcalistákkal és nyitott oldalon működő kereskedési értesítésekkel. Ezek az alkalmazások elérhetők a Vercelen. A Khonodds élő adatokat tölt be. Az opcionális napi összefoglaló a szerveren fut. Minden eszközt külön kell csatlakoztatni. A Web Push macOS-en, Brave-ben tesztelve. Telefonos kézbesítés még nincs tesztelve.", "pl": "Khonsolve · Khonrelay · Khonodds. Khonrelay zbiera oficjalne wiadomości AI, wydania i status usług z eksportem RSS. Khonodds służy do analizy Polymarket, obserwowania portfeli i alertów przy otwartej stronie. Te aplikacje są dostępne na Vercelu. Khonodds pobiera dane na żywo. Opcjonalne codzienne podsumowanie działa na serwerze. Każde urządzenie wymaga osobnej rejestracji. Web Push przetestowano w Brave na macOS. Dostarczenia na telefony jeszcze nie testowano.", "cs": "Khonsolve · Khonrelay · Khonodds. Khonrelay sbírá oficiální AI novinky, vydání a stav služeb s RSS exportem. Khonodds slouží ke čtení dat Polymarketu, sledování peněženek a upozornění při otevřené stránce. Tyto aplikace jsou dostupné na Vercelu. Khonodds načítá živá data. Volitelný denní přehled běží na serveru. Každé zařízení je třeba připojit zvlášť. Web Push je otestovaný v Brave na macOS. Doručení na telefonech zatím ne.", "de": "Khonsolve · Khonrelay · Khonodds. Khonrelay sammelt offizielle KI-Nachrichten, Releases und Statusmeldungen mit RSS-Export. Khonodds bietet Polymarket-Recherche, Wallet-Beobachtungslisten und Handelshinweise bei geöffneter Seite. Diese Apps sind auf Vercel verfügbar. Khonodds lädt Live-Daten. Eine optionale tägliche Zusammenfassung läuft auf dem Server. Jedes Gerät muss einzeln verbunden werden. Web Push wurde in Brave unter macOS getestet. Die Zustellung auf Handys wurde noch nicht getestet."}).forEach(([lang,text])=>topics.find(t=>t.id==='projects')[lang]=text);
  Object.entries({"en": "Khonstash is a Steam item watchlist with manual EUR price checks, fee estimates, local notes and backup export. Target notices appear after a check. It does not trade, boost hours or monitor prices when closed.", "sk": "Khonstash je watchlist Steam itemov s manuálnou kontrolou cien v EUR, odhadom poplatkov, lokálnymi poznámkami a exportom zálohy. Upozornenie na cieľovú cenu sa zobrazí po kontrole. Appka neobchoduje, nenafukuje odohrané hodiny a nesleduje ceny po zatvorení.", "hu": "A Khonstash Steam-tárgyak figyelőlistája, kézi EUR-árellenőrzéssel, díjbecsléssel, helyi jegyzetekkel és biztonsági mentéssel. A célárjelzés ellenőrzés után jelenik meg. Nem kereskedik, nem növeli mesterségesen a játékidőt, és bezárva nem figyeli az árakat.", "pl": "Khonstash to lista obserwowanych przedmiotów Steam z ręcznym sprawdzaniem cen w EUR, szacunkiem opłat, lokalnymi notatkami i kopią zapasową. Alert ceny docelowej pojawia się po sprawdzeniu. Aplikacja nie handluje, nie nabija godzin i nie śledzi cen po zamknięciu.", "cs": "Khonstash je seznam sledovaných Steam předmětů s ruční kontrolou cen v EUR, odhadem poplatků, místními poznámkami a exportem zálohy. Upozornění na cílovou cenu se zobrazí po kontrole. Aplikace neobchoduje, nenavyšuje odehrané hodiny a nesleduje ceny po zavření.", "de": "Khonstash ist eine Merkliste für Steam-Gegenstände mit manuellen EUR-Preisabfragen, Gebührenschätzung, lokalen Notizen und Sicherungsexport. Zielpreishinweise erscheinen nach einer Abfrage. Die App handelt nicht, erhöht keine Spielstunden und überwacht keine Preise im Hintergrund."}).forEach(([lang,text])=>topics.find(t=>t.id==='projects')[lang]+=' '+text);
  topics.push({"id":"proof","keys":["khonproof","benchmark","benchmarks","evaluation","evaluacia","browser course","skill lab"],"project":"proof","en":"A small lab for agent decisions, browser tasks, skill comparisons, deploy checks and claims. It includes 20 browser tasks and measured reports. Model tests run locally with your own API key.","sk":"Malé laboratórium na rozhodovanie agentov, browser úlohy, porovnávanie skills, kontroly nasadenia a tvrdení. 20 browser úloh a import meraných reportov. Jev aj jednoduchý skript majú zverejnené výsledky vrátane chýb. Modelové testy bežia lokálne s vlastným API kľúčom. Malá vzorka, nie všeobecný rebríček modelov.","hu":"Kis labor az ágensek döntéseihez, böngészőfeladatokhoz, utasítások összehasonlításához, telepítések és állítások ellenőrzéséhez. 20 böngészőfeladat és mérési jelentések importálása. A Jev és egy egyszerű szkript eredményei a hibákkal együtt láthatók. A modelltesztek helyben futnak saját API-kulccsal. Kis minta, nem általános modellrangsor.","pl":"Małe laboratorium decyzji agentów, zadań przeglądarkowych, porównań instrukcji, wdrożeń i twierdzeń. 20 zadań przeglądarkowych i import raportów. Wyniki Jev i prostego skryptu zawierają również błędy. Testy modeli działają lokalnie z własnym kluczem API. Mała próbka, nie ogólny ranking modeli.","de":"Ein kleines Labor für Agentenentscheidungen, Browseraufgaben, Anweisungsvergleiche, Deployments und Behauptungen. 20 Browseraufgaben und Import gemessener Berichte. Ergebnisse von Jev und einem einfachen Skript zeigen auch Fehler. Modelltests laufen lokal mit eigenem API-Schlüssel. Kleine Stichprobe, keine allgemeine Modellrangliste.","es":"Un pequeño laboratorio de decisiones de agentes, tareas de navegador, instrucciones, despliegues y afirmaciones. 20 tareas de navegador e importación de informes. Los resultados de Jev y un script sencillo incluyen los fallos. Las pruebas de modelos se ejecutan localmente con una clave API propia. Una muestra pequeña, no una clasificación general.","cs":"Malá laboratoř pro rozhodování agentů, úlohy v prohlížeči, porovnání instrukcí, nasazení a tvrzení. 20 úloh v prohlížeči a import naměřených reportů. Výsledky Jev i jednoduchého skriptu zahrnují také chyby. Modelové testy běží lokálně s vlastním API klíčem. Malý vzorek, nikoli obecný žebříček modelů."});
  const spanishTopics = {"site": "Este portfolio usa HTML, CSS y JavaScript, con terminal, temas claro y oscuro y una guía local en varios idiomas. Se publica desde GitHub en Vercel.", "discovery": "Rutinas semanales para recomendar cuentas de X y seguir hasta tres desarrolladores relevantes de GitHub. Un agente de IA revisa candidatos. La primera ejecución programada aún no está verificada.", "signal": "Khonrelay reúne noticias oficiales de IA, lanzamientos y estado de servicios con exportación RSS. Khonodds permite investigar Polymarket y recibir avisos con la página abierta. Ambas están en Vercel. Un resumen diario opcional se ejecuta en el servidor. Hay que registrar cada dispositivo por separado. Web Push probado en Brave para macOS. El envío a teléfonos aún no se ha probado.", "steam": "Khonstash permite consultar manualmente precios EUR de objetos Steam, estimar comisiones y guardar notas y copias. Los avisos de precio aparecen tras una consulta. No opera, no aumenta horas ni vigila precios al cerrar.", "thinkroom": "Khonsolve es un taller gratuito con 15 ejercicios de código, depuración, lógica, prompts y agent skills. Ofrece pruebas locales de JavaScript, TypeScript y Python, pistas graduales y notas. Código público en GitHub."};
  topics.forEach(topic=>{if(spanishTopics[topic.id])topic.es=spanishTopics[topic.id];});
  Object.entries({"en": "Optional Jev reading order uses precomputed scores. It does not hide posts or change alerts.", "sk": "Voliteľné poradie od Jev používa vopred vypočítané skóre. Neskrýva príspevky ani nemení upozornenia.", "hu": "Az opcionális Jev-sorrend előre kiszámított pontszámokat használ. Nem rejt el bejegyzéseket és nem módosítja az értesítéseket.", "pl": "Opcjonalna kolejność Jev korzysta z wcześniej obliczonych ocen. Nie ukrywa wpisów ani nie zmienia powiadomień.", "de": "Die optionale Jev-Reihenfolge nutzt vorberechnete Bewertungen. Beiträge bleiben sichtbar und Benachrichtigungen unverändert.", "es": "El orden opcional de Jev usa puntuaciones precalculadas. No oculta publicaciones ni cambia los avisos.", "cs": "Volitelné pořadí od Jev používá předem vypočítaná skóre. Neskrývá příspěvky ani nemění upozornění."}).forEach(([lang,text])=>{topics.find(t=>t.id==='signal')[lang]+=' '+text;});
  const spanishKeys={work:['trabajo','soporte','que haces','integraciones'],projects:['proyectos','proyecto'],about:['quien eres','sobre ti','nombre'],study:['universidad','tesis','estudios'],contact:['contacto','correo','contratar'],games:['juegos','juegas'],ai:['inteligencia artificial','modelos'],spotify:['musica'],site:['esta web','este sitio']};
  topics.forEach(topic=>topic.keys.push(...(spanishKeys[topic.id]||[])));
  // These packs use topic IDs so inserting a topic cannot shift the translations.
  for (const [language, pack] of Object.entries(localeData.EXTRA_LOCALE_PACKS)) {
    locales[language] = pack.guide;
    for (const topic of topics) {
      topic.translations ||= {};
      topic.translations[language] = pack.guide.answers[topic.id];
      topic.keys.push(...(pack.guide.keywords[topic.id] || []));
    }
  }
  const matchesKey = (question,key) => {
    const value=normalize(key);
    if (!value) return false;
    // Chinese and Japanese do not require spaces between words.
    return /[\p{Script=Han}\p{Script=Hiragana}\p{Script=Katakana}]/u.test(value)
      ? question.includes(value) : (' '+question+' ').includes(' '+value+' ');
  };
  const englishUI=['A small guide to Patrick’s work.','Prepared answers, not an AI model. Questions stay in this tab and disappear on reload.','Answer language','Ask about the portfolio…','Send question','Clear chat','Open project ↗','View section ↗','Work','Projects','About me','LOCAL GUIDE · NO API','Close guide'];
  const slovakUI=['Malý sprievodca Patrickovou prácou.','Pripravené odpovede, nie AI model. Otázky zostávajú v tejto karte a po obnovení zmiznú.','Jazyk odpovedí','Opýtaj sa na portfólio…','Odoslať otázku','Vymazať chat','Otvoriť projekt ↗','Pozrieť sekciu ↗','Práca','Projekty','O mne','LOKÁLNY SPRIEVODCA · BEZ API','Zavrieť'];
  function ui(language){return locales[language]?.ui||(language==='sk'?slovakUI:englishUI);}
  function answer(text, language) {
    const q = normalize(text);
    const sk = language === 'sk';
    const loc=locales[language];
    if (loc?.privacyKeys?.some(key=>matchesKey(q,key))) return {text:loc.privacy};
    if (loc?.greetings?.some(key=>q===normalize(key))) return {text:loc.greeting};
    if (/\b(contrasena|secreto|salario|direccion|password|secret|salary|address|heslo|plat|bydlisko|jelszo|fizetes|haslo|wynagrodzenie|passwort|gehalt)\b/.test(q)) return {text:loc?.privacy||(sk?'Poznám len verejné informácie z portfólia. Súkromné údaje tu nenájdeš.':'I only know the public portfolio. Private details aren’t available here.')};
    if (/\b(hola|buenas|hello|hi|hey|ahoj|cau|szia|udv|czesc|hej|hallo|servus)\b/.test(q) && q.split(' ').length < 4) return {text:loc?.greeting||(sk?'Ahoj! Som lokálny sprievodca portfóliom, nie Patrick ani AI model. Čo ťa zaujíma?':'Hey! I’m a local portfolio guide, not Patrick or an AI model. What would you like to explore?')};
    const scored = topics.map(topic => ({topic,score:topic.keys.reduce((score,key)=>score+(matchesKey(q,key)?key.includes(' ')?3:2:0),0)})).sort((a,b)=>b.score-a.score);
    if (!scored[0].score) return {text:loc?.fallback||(sk?'Toto neviem spoľahlivo priradiť. Skús prácu, projekty, C++, Spotify alebo kontakt. Poznám iba pripravené informácie z tohto webu.':'I can’t reliably match that question. Try work, projects, C++, Spotify, or contact. I only know the prepared information on this site.')};
    const t=scored[0].topic;return {text:t.translations?.[language]||t[language]||t.en,project:t.project,section:t.section};
  }
  if (typeof module !== 'undefined' && module.exports) module.exports={answer,topics,ui};
  if (typeof document === 'undefined') return;
  const dialog=document.querySelector('#guide-dialog'),log=document.querySelector('#guide-log'),input=document.querySelector('#guide-question'),lang=document.querySelector('#guide-language');
  // iOS keyboards shrink the visual viewport, not the layout viewport.
  function fitGuideViewport(){
    const viewport=window.visualViewport;
    if(!viewport)return;
    dialog.style.setProperty('--guide-visible-height',`${viewport.height}px`);
    dialog.style.setProperty('--guide-visible-top',`${viewport.offsetTop}px`);
    dialog.classList.toggle('guide-typing',document.activeElement===input&&viewport.height<window.innerHeight*.8);
    if(dialog.open&&dialog.contains(document.activeElement))requestAnimationFrame(()=>document.activeElement.scrollIntoView({block:'nearest'}));
  }
  window.visualViewport?.addEventListener('resize',fitGuideViewport);
  window.visualViewport?.addEventListener('scroll',fitGuideViewport);
  fitGuideViewport();
  function translateUI(){
    const t=ui(lang.value).map(text=>localeData.directionalText(text,lang.value));dialog.lang=lang.value;dialog.dir=localeData.languageDirection(lang.value);
    const pageText=text=>globalThis.PortfolioI18n?.t(text,lang.value)||text;
    const tabNames={'terminal-dialog':'Terminal','guide-dialog':'Ask khonsu','email-dialog':'Email'};
    dialog.querySelector('.panel-nav').setAttribute('aria-label',pageText('Portfolio tools'));
    dialog.querySelectorAll('[data-panel]').forEach(button=>button.textContent=pageText(tabNames[button.dataset.panel]));
    document.querySelector('#guide-title').textContent=globalThis.PortfolioI18n?.t('☾ ask khonsu',lang.value)||'☾ ask khonsu';
    log.setAttribute('aria-label',globalThis.PortfolioI18n?.t('Conversation',lang.value)||'Conversation');
    document.querySelectorAll('.guide-intro p').forEach((p,i)=>p.textContent=t[i]);
    document.querySelector('label[for="guide-language"]').textContent=t[2];input.placeholder=t[3];document.querySelector('label[for="guide-question"]').textContent=t[3];
    document.querySelector('#guide-form button').setAttribute('aria-label',t[4]);document.querySelector('#guide-clear').textContent=t[5];
    document.querySelectorAll('[data-question]').forEach((b,i)=>{if(i<3)b.textContent=t[8+i];b.dir=i===3?'ltr':'auto';});
    document.querySelector('#guide-dialog .terminal-bottom span').textContent=t[11];document.querySelector('[data-close="guide-dialog"]').setAttribute('aria-label',t[12]);
    try{localStorage.setItem('khonsu-guide-language',lang.value);}catch{}
  }
  try{const stored=localStorage.getItem('khonsu-guide-language');const preferred=[...lang.options].some(o=>o.value===stored)?stored:(globalThis.PortfolioI18n?.language||navigator.language.split('-')[0]);if([...lang.options].some(o=>o.value===preferred))lang.value=preferred;}catch{}
  lang.addEventListener('change',translateUI);translateUI();
  window.addEventListener('portfolio:language',()=>{lang.value=PortfolioI18n.language;lang.dispatchEvent(new Event('change'));});
  function append(text, who, result) {
    const row=document.createElement('div');row.className='guide-message '+who;if(who==='guide'){row.lang=lang.value;row.dir=localeData.languageDirection(lang.value);}else row.dir='auto';
    const p=document.createElement('p');p.textContent=who==='guide'?localeData.directionalText(text,lang.value):text;row.append(p);
    if(result&&(result.project||result.section)){
      // Project notes and sections stay on this page, so they use → rather than the outside-link ↗.
      const button=document.createElement('button');button.type='button';button.className='guide-action';button.textContent=ui(lang.value)[result.project?6:7].replace('↗','→');
      button.addEventListener('click',()=>{dialog.close();if(result.project)showProject(result.project);else document.getElementById(result.section).scrollIntoView({behavior:document.documentElement.classList.contains('motion-off')?'instant':'smooth'});});row.append(button);
    }
    log.append(row);while(log.children.length>30)log.firstElementChild.remove();row.scrollIntoView({block:'nearest',behavior:'instant'});
  }
  function ask(text){if(!text.trim())return;append(text.trim().slice(0,300),'visitor');const result=answer(text,lang.value);append(result.text,'guide',result);input.value='';}
  document.querySelector('#guide-launcher').addEventListener('click',()=>window.PortfolioPanels.open('guide-dialog',matchMedia('(pointer: coarse)').matches?null:'#guide-question'));
  document.querySelector('#guide-form').addEventListener('submit',e=>{e.preventDefault();ask(input.value);});
  document.querySelectorAll('[data-question]').forEach(button=>button.addEventListener('click',()=>ask(button.dataset.question)));
  document.querySelector('#guide-clear').addEventListener('click',()=>{log.replaceChildren();input.value='';input.focus();});
})();
