/* A local, rule-based portfolio guide. No model, network calls or chat storage. */
(function () {
  const normalize = text => text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/ł/g,'l').replace(/ß/g,'ss').replace(/[^a-z0-9+ ]/g, ' ').replace(/\s+/g, ' ').trim();
  const topics = [
    {id:'work', keys:['what do you do','co robis','cim sa zivis','l2','support','integration','integrations','integracie','integracii','luigi','lbx','praca','praci','pracujes','work','job','audit'], en:'Patrick works as a Customer Support Partner L2 at Luigi’s Box. He investigates browser behaviour, APIs, product feeds and analytics, audits integrations, verifies fixes, and prepares engineering handovers. Luigi’s Box builds search and product discovery for e-commerce.', sk:'Patrick pracuje ako Customer Support Partner L2 v Luigi’s Box. Rieši správanie webu, API, produktové feedy a analytiku, robí audity integrácií, overuje opravy a pripravuje podklady pre vývojárov. Luigi’s Box tvorí vyhľadávanie a odporúčanie produktov pre e-shopy.', section:'about'},
    {id:'spotify', keys:['spotify','rotation','playlist','hudba','music'], en:'His Spotify rotation is a local Python script that combines favourite and recently played tracks into a private playlist. It runs on a schedule without recurring AI calls. The source is not public.', sk:'Spotify rotation je lokálny Python skript, ktorý skladá súkromný playlist z obľúbených a nedávno počúvaných skladieb. Beží podľa rozvrhu bez priebežných AI volaní. Zdrojový kód nie je verejný.', project:'rotation'},
    {id:'dots', keys:['dots','spring','react'], en:'Dots is an earlier web game with a React frontend and a Spring Boot backend. It’s a snapshot of Patrick’s earlier full-stack work, not a recently maintained product.', sk:'Dots je staršia webová hra s React frontendom a Spring Boot backendom. Je to ukážka Patrickovej skoršej full-stack práce, nie aktuálne udržiavaný produkt.', project:'dots'},
    {id:'bot', keys:['bot','cslys','discord bot','music bot'], en:'CSLYS is an earlier JavaScript Discord bot with music playback. The repository is historical, so current Discord and music-service compatibility is not guaranteed.', sk:'CSLYS je starší JavaScript Discord bot s prehrávaním hudby. Repozitár je historický, takže kompatibilita s dnešnými API nie je overená.', project:'bot'},
    {id:'cpp', keys:['c++','cpp','ipc','process','processes','proces','procesy'], en:'C++ and Counter-Strike got Patrick into programming. For a code example, there’s also his university team project on inter-process communication.', sk:'K programovaniu sa Patrick dostal cez C++ a Counter-Strike. Ukážkou kódu je aj univerzitný tímový projekt medziprocesovej komunikácie.', project:'ipc'},
    {id:'openai', keys:['openai','tibo','codex','fan','fandi','fandis','thsottiaux'], en:'He follows Tibo closely for the pace of his work at OpenAI and how he talks about what they’re building. This is a personal interest, not an affiliation.', sk:'Momentálne sleduje najmä Tiba. Páči sa mu tempo jeho práce v OpenAI a spôsob, akým hovorí o tom, čo tvoria. Ide o osobný záujem, nie pracovné prepojenie.', section:'now'},
    {id:'study', keys:['university','degree','thesis','tuke','ppo','reinforcement','school','skola','studium','diplomovka','diplomov','vzdelanie'], en:'Patrick has a master’s in Computer Science from TUKE. His thesis combined PPO reinforcement-learning agents and LLM-driven map generation for a multiplayer game.', sk:'Patrick má magisterské vzdelanie v informatike z TUKE. V diplomovej práci spojil PPO reinforcement-learning agentov s generovaním máp pomocou LLM pre multiplayerovú hru.', section:'now'},
    {id:'projects', keys:['projects','project','projekty','projekt','built','builds','portfolio'], en:'Start with Spotify rotation for a current personal experiment, Dots for React and Java, CSLYS for a Discord bot, or inter-process communication for C++. Most public repositories are older.', sk:'Pozri Spotify rotation ako aktuálny osobný experiment, Dots pre React a Javu, CSLYS pre Discord bota alebo medziprocesovú komunikáciu pre C++. Väčšina verejných repozitárov je staršia.', section:'projects'},
    {id:'contact', keys:['contact','kontakt','email','hire','hiring','reach','discord','github','twitter','linkedin'], en:'You can find Patrick on GitHub as khons-hu, on X as @ptr1337_, and on Discord as khons.hu. I can show you those links, but I can’t send a message or speak for him.', sk:'Patrick je na GitHube ako khons-hu, na X ako @ptr1337_ a na Discorde ako khons.hu. Ukážem ti odkazy, ale nemôžem poslať správu ani hovoriť v jeho mene.', section:'contact'},
    {id:'about', keys:['kto si','povedz mi o sebe','who are you','about','who','patrick','khonsu','yourself','kto','tebe','zacal','zaciatky','started','background','name','nickname','handle','moon knight','moonknight','meno','prezyvka','nev','nazwa','pseudonim','jmeno'], en:'Patrick Obrtal, online as khonsu. He started using the name around 2022, inspired by Moon Knight. He started with C++ and Counter-Strike, studied Computer Science at TUKE, and now works as a Customer Support Partner L2 at Luigi’s Box. He also experiments with coding agents and still plays CS2.', sk:'Patrick Obrtal, online khonsu. Meno používa približne od roku 2022, inšpirované Moon Knightom. Začal s C++ a Counter-Strike, vyštudoval informatiku na TUKE a dnes pracuje ako Customer Support Partner L2 v Luigi’s Box. Skúša coding agentov a stále hrá CS2.', section:'about'},
    {id:'ai', keys:['agi','rsi','agents','agent','ai','models','modely','llm'], en:'He follows AGI, recursive self-improvement, and new model releases, and tries coding agents in his own work. His interest in learning systems also appears in his PPO thesis project.', sk:'Sleduje AGI, rekurzívne sebazlepšovanie a nové modely. Coding agentov skúša vo vlastnej práci. Learning systémom sa venoval aj v diplomovke s PPO.', section:'now'},
    {id:'games', keys:['cs2','counter strike','games','gaming','hry','hras','hrava'], en:'Counter-Strike is part of both his programming background and his free time. For ranks and match stats, you’ll have to ask Patrick. This guide didn’t queue with him.', sk:'Counter-Strike patrí k jeho programátorským začiatkom aj voľnému času. Rank a štatistiky sa musíš opýtať Patricka. Tento sprievodca s ním ešte nehral.', section:'about'}
  ];
  const locales=typeof module!=='undefined'&&module.exports?require('./guide-locales.js'):GUIDE_LOCALES;
  const extraKeys={work:['mit dolgozol','mivel foglalkozol','munka','dolgozik','prace','pracujesz','pracuji','co delas','prace','arbeit','beruf','was machst du','integracio','integracje'],spotify:['zene','lejatszasi lista','muzyka','hudba','musik'],cpp:['folyamatok','procesami','prozesse'],study:['egyetem','diploma','tanult','wyksztalcenie','studia','uczelni','vzdelani','diplomova','abschluss','studium','universitat'],projects:['projektek','projekteken','projektjeid','projektjei','projektet','projektach','projektami','jakimi projektami','projektow','projektech','projekten','projekte','zbudowal'],contact:['kapcsolat','elerhetoseg','elerni','skontaktowac','zatrudnic','erreichen','kontaktovat'],about:['ki vagy','kicsoda','magadrol','kim jestes','o sobie','wer bist du','uber dich','kdo jsi','o sobe'],ai:['mesterseges intelligencia','modellek','sztuczna inteligencja','modelle','kunstliche intelligenz'],games:['jatekok','jatszol','gry','grasz','hrajes','spiele','spielst']};
  topics.forEach((topic,index)=>{topic.keys.push(...(extraKeys[topic.id]||[]));Object.keys(locales).forEach(lang=>topic[lang]=locales[lang].answers[index]);});
  topics.push(...[{"id": "site", "keys": ["this site", "this website", "portfolio site", "terminal", "theme", "themes", "tento web", "weboldal", "strona", "diese website"], "project": "portfolio", "en": "This portfolio uses HTML, CSS and JavaScript, with terminal navigation, light and dark themes, and a local guide in six languages. Updates deploy from GitHub to Vercel.", "sk": "Toto portfólio používa HTML, CSS a JavaScript. Má terminál, svetlú a tmavú tému a lokálneho sprievodcu v šiestich jazykoch. Zmeny sa publikujú z GitHubu na Vercel.", "hu": "Ez a portfólió HTML-t, CSS-t és JavaScriptet használ. Terminált, világos és sötét témát, valamint hatnyelvű helyi útmutatót tartalmaz. A frissítések GitHubról kerülnek a Vercelre.", "pl": "To portfolio używa HTML, CSS i JavaScript. Ma terminal, jasny i ciemny motyw oraz lokalny przewodnik w sześciu językach. Aktualizacje trafiają z GitHuba na Vercel.", "cs": "Toto portfolio používá HTML, CSS a JavaScript. Má terminál, světlé a tmavé téma a místního průvodce v šesti jazycích. Změny se publikují z GitHubu na Vercel.", "de": "Dieses Portfolio nutzt HTML, CSS und JavaScript, mit Terminal, hellem und dunklem Design und einem lokalen Guide in sechs Sprachen. Updates werden von GitHub auf Vercel veröffentlicht."}, {"id": "discovery", "keys": ["discovery", "routines", "autofollow", "weekly workflows", "rotation stuff", "automatizacie", "automatizace", "automatyzacja"], "project": "discovery", "en": "Discovery routines are weekly workflows for X recommendations and up to three relevant GitHub follows. They review candidates with an AI agent. The first scheduled run has not yet been verified.", "sk": "Discovery routines sú týždenné workflowy pre odporúčania účtov na X a sledovanie najviac troch relevantných vývojárov na GitHube. Kandidátov posudzuje AI agent. Prvý naplánovaný beh ešte nebol overený.", "hu": "A Discovery routines heti munkafolyamatokat jelent X-fiókok ajánlására és legfeljebb három releváns GitHub-fejlesztő követésére. A jelölteket AI-ágens értékeli. Az első ütemezett futás még nincs ellenőrizve.", "pl": "Discovery routines to cotygodniowe rekomendacje kont na X i obserwowanie maksymalnie trzech odpowiednich programistów na GitHubie. Kandydatów ocenia agent AI. Pierwszy zaplanowany przebieg nie został jeszcze zweryfikowany.", "cs": "Discovery routines jsou týdenní workflowy pro doporučení účtů na X a sledování nejvýše tří relevantních vývojářů na GitHubu. Kandidáty posuzuje AI agent. První naplánovaný běh ještě nebyl ověřen.", "de": "Discovery routines empfehlen wöchentlich X-Konten und folgen bis zu drei passenden GitHub-Entwicklern. Ein KI-Agent prüft die Kandidaten. Der erste geplante Durchlauf wurde noch nicht verifiziert."}]);
  Object.entries({"en": "Current projects include this portfolio and Discovery routines. ", "sk": "Aktuálne projekty zahŕňajú toto portfólio a Discovery routines. ", "hu": "A jelenlegi projektek közé tartozik ez a portfólió és a Discovery routines. ", "pl": "Aktualne projekty obejmują to portfolio i Discovery routines. ", "cs": "Aktuální projekty zahrnují toto portfolio a Discovery routines. ", "de": "Zu den aktuellen Projekten gehören dieses Portfolio und Discovery routines. "}).forEach(([lang,text])=>{topics.find(t=>t.id==='projects')[lang]=text+topics.find(t=>t.id==='projects')[lang];});
  const englishUI=['A small guide to Patrick’s work.','Prepared answers, not an AI model. Questions stay in this tab and disappear on reload.','Answer language','Ask about the portfolio…','Send question','Clear chat','Open project ↗','View section ↗','Work','Projects','About me','LOCAL GUIDE · NO API','Close guide'];
  const slovakUI=['Malý sprievodca Patrickovou prácou.','Pripravené odpovede, nie AI model. Otázky zostávajú v tejto karte a po obnovení zmiznú.','Jazyk odpovedí','Opýtaj sa na portfólio…','Odoslať otázku','Vymazať chat','Otvoriť projekt ↗','Pozrieť sekciu ↗','Práca','Projekty','O mne','LOKÁLNY SPRIEVODCA · BEZ API','Zavrieť'];
  function ui(language){return locales[language]?.ui||(language==='sk'?slovakUI:englishUI);}
  function answer(text, language) {
    const q = normalize(text);
    const sk = language === 'sk';
    const loc=locales[language];
    if (/\b(password|secret|salary|address|heslo|plat|bydlisko|jelszo|fizetes|haslo|wynagrodzenie|passwort|gehalt)\b/.test(q)) return {text:loc?.privacy||(sk?'Poznám len verejné informácie z portfólia. Súkromné údaje tu nenájdeš.':'I only know the public portfolio. Private details aren’t available here.')};
    if (/\b(hello|hi|hey|ahoj|cau|szia|udv|czesc|hej|hallo|servus)\b/.test(q) && q.split(' ').length < 4) return {text:loc?.greeting||(sk?'Ahoj! Som lokálny sprievodca portfóliom, nie Patrick ani AI model. Čo ťa zaujíma?':'Hey! I’m a local portfolio guide, not Patrick or an AI model. What would you like to explore?')};
    const scored = topics.map(topic => ({topic,score:topic.keys.reduce((score,key)=>score+((' '+q+' ').includes(' '+key+' ')?key.includes(' ')?3:2:0),0)})).sort((a,b)=>b.score-a.score);
    if (!scored[0].score) return {text:loc?.fallback||(sk?'Toto neviem spoľahlivo priradiť. Skús prácu, projekty, C++, Spotify alebo kontakt. Poznám iba pripravené informácie z tohto webu.':'I can’t reliably match that question. Try work, projects, C++, Spotify, or contact. I only know the prepared information on this site.')};
    const t=scored[0].topic;return {text:t[language]||t.en,project:t.project,section:t.section};
  }
  if (typeof module !== 'undefined' && module.exports) module.exports={answer,topics,ui};
  if (typeof document === 'undefined') return;
  const dialog=document.querySelector('#guide-dialog'),log=document.querySelector('#guide-log'),input=document.querySelector('#guide-question'),lang=document.querySelector('#guide-language');
  function translateUI(){
    const t=ui(lang.value);dialog.lang=lang.value;
    document.querySelectorAll('.guide-intro p').forEach((p,i)=>p.textContent=t[i]);
    document.querySelector('label[for="guide-language"]').textContent=t[2];input.placeholder=t[3];document.querySelector('label[for="guide-question"]').textContent=t[3];
    document.querySelector('#guide-form button').setAttribute('aria-label',t[4]);document.querySelector('#guide-clear').textContent=t[5];
    document.querySelectorAll('[data-question]').forEach((b,i)=>{if(i<3)b.textContent=t[8+i];});
    document.querySelector('#guide-dialog .terminal-bottom span').textContent=t[11];document.querySelector('[data-close="guide-dialog"]').setAttribute('aria-label',t[12]);
    try{localStorage.setItem('khonsu-guide-language',lang.value);}catch{}
  }
  try{const stored=localStorage.getItem('khonsu-guide-language');const preferred=stored||navigator.language.split('-')[0];if([...lang.options].some(o=>o.value===preferred))lang.value=preferred;}catch{}
  lang.addEventListener('change',translateUI);translateUI();
  function append(text, who, result) {
    const row=document.createElement('div');row.className='guide-message '+who;if(who==='guide')row.lang=lang.value;
    const p=document.createElement('p');p.textContent=text;row.append(p);
    if(result&&(result.project||result.section)){
      const button=document.createElement('button');button.className='guide-action';button.textContent=ui(lang.value)[result.project?6:7];
      button.addEventListener('click',()=>{dialog.close();if(result.project)showProject(result.project);else document.getElementById(result.section).scrollIntoView({behavior:document.documentElement.classList.contains('motion-off')?'instant':'smooth'});});row.append(button);
    }
    log.append(row);while(log.children.length>30)log.firstElementChild.remove();row.scrollIntoView({block:'nearest',behavior:'instant'});
  }
  function ask(text){if(!text.trim())return;append(text.trim().slice(0,300),'visitor');const result=answer(text,lang.value);append(result.text,'guide',result);input.value='';}
  document.querySelector('#guide-launcher').addEventListener('click',()=>{dialog.showModal();input.focus();});
  document.querySelector('#guide-form').addEventListener('submit',e=>{e.preventDefault();ask(input.value);});
  document.querySelectorAll('[data-question]').forEach(button=>button.addEventListener('click',()=>ask(button.dataset.question)));
  document.querySelector('#guide-clear').addEventListener('click',()=>{log.replaceChildren();input.value='';input.focus();});
})();
