/* A local, rule-based portfolio guide. No model, network calls or chat storage. */
(function () {
  const normalize = text => text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9+ ]/g, ' ').replace(/\s+/g, ' ').trim();
  const topics = [
    {id:'work', keys:['what do you do','co robis','cim sa zivis','l2','support','integration','integrations','integracie','integracii','luigi','lbx','praca','praci','pracujes','work','job','audit'], en:'Patrick works in L2 technical support and integrations at Luigi’s Box. He investigates browser behaviour, APIs, product feeds and analytics, audits integrations, verifies fixes, and prepares engineering handovers. Luigi’s Box builds search and product discovery for e-commerce.', sk:'Patrick pracuje v L2 technickej podpore a integráciách v Luigi’s Box. Rieši správanie webu, API, produktové feedy a analytiku, robí audity integrácií, overuje opravy a pripravuje podklady pre vývojárov. Luigi’s Box tvorí vyhľadávanie a odporúčanie produktov pre e-shopy.', section:'about'},
    {id:'spotify', keys:['spotify','rotation','playlist','hudba','music'], en:'His Spotify rotation is a local Python script that combines favourite and recently played tracks into a private playlist. It runs on a schedule without recurring AI calls. The source is not public.', sk:'Spotify rotation je lokálny Python skript, ktorý skladá súkromný playlist z obľúbených a nedávno počúvaných skladieb. Beží podľa rozvrhu bez priebežných AI volaní. Zdrojový kód nie je verejný.', project:'rotation'},
    {id:'dots', keys:['dots','spring','react'], en:'Dots is an earlier web game with a React frontend and a Spring Boot backend. It’s a snapshot of Patrick’s earlier full-stack work, not a recently maintained product.', sk:'Dots je staršia webová hra s React frontendom a Spring Boot backendom. Je to ukážka Patrickovej skoršej full-stack práce, nie aktuálne udržiavaný produkt.', project:'dots'},
    {id:'bot', keys:['bot','cslys','discord bot','music bot'], en:'CSLYS is an earlier JavaScript Discord bot with music playback. The repository is historical, so current Discord and music-service compatibility is not guaranteed.', sk:'CSLYS je starší JavaScript Discord bot s prehrávaním hudby. Repozitár je historický, takže kompatibilita s dnešnými API nie je overená.', project:'bot'},
    {id:'cpp', keys:['c++','cpp','ipc','process','processes','proces','procesy'], en:'C++ and Counter-Strike got Patrick into programming. For a code example, there’s also his university team project on inter-process communication.', sk:'K programovaniu sa Patrick dostal cez C++ a Counter-Strike. Ukážkou kódu je aj univerzitný tímový projekt medziprocesovej komunikácie.', project:'ipc'},
    {id:'openai', keys:['openai','tibo','codex','fan','fandi','fandis','thsottiaux'], en:'He’s currently a fan of OpenAI and Tibo: the direction of Codex, the pace of development, and how Tibo talks about the work. Patrick uses Codex himself. This is a personal preference, not an affiliation.', sk:'Momentálne fandí OpenAI a Tibovi. Páči sa mu smerovanie Codexu, tempo vývoja a Tibova komunikácia. Codex sám používa. Ide o osobnú preferenciu, nie pracovné prepojenie.', section:'now'},
    {id:'study', keys:['university','degree','thesis','tuke','ppo','reinforcement','school','skola','studium','diplomovka','diplomov','vzdelanie'], en:'Patrick has a master’s in Computer Science from TUKE. His thesis combined PPO reinforcement-learning agents and LLM-driven map generation for a multiplayer game.', sk:'Patrick má magisterské vzdelanie v informatike z TUKE. V diplomovej práci spojil PPO reinforcement-learning agentov s generovaním máp pomocou LLM pre multiplayerovú hru.', section:'now'},
    {id:'projects', keys:['projects','project','projekty','projekt','built','builds','portfolio'], en:'Start with Spotify rotation for a current personal experiment, Dots for React and Java, CSLYS for a Discord bot, or inter-process communication for C++. Most public repositories are older.', sk:'Pozri Spotify rotation ako aktuálny osobný experiment, Dots pre React a Javu, CSLYS pre Discord bota alebo medziprocesovú komunikáciu pre C++. Väčšina verejných repozitárov je staršia.', section:'projects'},
    {id:'contact', keys:['contact','kontakt','email','hire','hiring','reach','discord','github','twitter','linkedin'], en:'You can find Patrick on GitHub as khons-hu, on X as @ptr1337_, and on Discord as khons.hu. I can show you those links, but I can’t send a message or speak for him.', sk:'Patrick je na GitHube ako khons-hu, na X ako @ptr1337_ a na Discorde ako khons.hu. Ukážem ti odkazy, ale nemôžem poslať správu ani hovoriť v jeho mene.', section:'contact'},
    {id:'about', keys:['kto si','povedz mi o sebe','who are you','about','who','patrick','khonsu','yourself','kto','tebe','zacal','zaciatky','started','background'], en:'Patrick Obrtal, online as khonsu. He started with C++ and Counter-Strike, studied Computer Science at TUKE, and now works on integrations at Luigi’s Box. He also experiments with coding agents and still plays CS2.', sk:'Patrick Obrtal, online khonsu. Začal s C++ a Counter-Strike, vyštudoval informatiku na TUKE a dnes pracuje na integráciách v Luigi’s Box. Skúša coding agentov a stále hrá CS2.', section:'about'},
    {id:'ai', keys:['agi','rsi','agents','agent','ai','models','modely','llm'], en:'He follows AGI, recursive self-improvement, and new model releases, and tries coding agents in his own work. His interest in learning systems also appears in his PPO thesis project.', sk:'Sleduje AGI, rekurzívne sebazlepšovanie a nové modely. Coding agentov skúša vo vlastnej práci. Learning systémom sa venoval aj v diplomovke s PPO.', section:'now'},
    {id:'games', keys:['cs2','counter strike','games','gaming','hry','hras','hrava'], en:'Counter-Strike is part of both his programming background and his free time. For ranks and match stats, you’ll have to ask Patrick. This guide didn’t queue with him.', sk:'Counter-Strike patrí k jeho programátorským začiatkom aj voľnému času. Rank a štatistiky sa musíš opýtať Patricka. Tento sprievodca s ním ešte nehral.', section:'about'}
  ];
  function answer(text, language) {
    const q = normalize(text);
    const sk = language === 'sk';
    if (/\b(password|secret|salary|address|heslo|plat|bydlisko)\b/.test(q)) return {text:sk?'Poznám len verejné informácie z portfólia. Súkromné údaje tu nenájdeš.':'I only know the public portfolio. Private details aren’t available here.'};
    if (/\b(hello|hi|hey|ahoj|cau)\b/.test(q) && q.split(' ').length < 4) return {text:sk?'Ahoj! Som lokálny sprievodca portfóliom, nie Patrick ani AI model. Čo ťa zaujíma?':'Hey! I’m a local portfolio guide, not Patrick or an AI model. What would you like to explore?'};
    const scored = topics.map(topic => ({topic,score:topic.keys.reduce((score,key)=>score+((' '+q+' ').includes(' '+key+' ')?key.includes(' ')?3:2:0),0)})).sort((a,b)=>b.score-a.score);
    if (!scored[0].score) return {text:sk?'Toto neviem spoľahlivo priradiť. Skús prácu, projekty, C++, Spotify alebo Codex. Poznám iba pripravené informácie z tohto webu.':'I can’t reliably match that question. Try work, projects, C++, Spotify, or Codex. I only know the prepared information on this site.'};
    const t=scored[0].topic;return {text:sk?t.sk:t.en,project:t.project,section:t.section};
  }
  if (typeof module !== 'undefined' && module.exports) module.exports={answer};
  if (typeof document === 'undefined') return;
  const dialog=document.querySelector('#guide-dialog'),log=document.querySelector('#guide-log'),input=document.querySelector('#guide-question'),lang=document.querySelector('#guide-language');
  function append(text, who, result) {
    const row=document.createElement('div');row.className='guide-message '+who;
    const p=document.createElement('p');p.textContent=text;row.append(p);
    if(result&&(result.project||result.section)){
      const button=document.createElement('button');button.className='guide-action';button.textContent=lang.value==='sk'?(result.project?'Otvoriť projekt ↗':'Pozrieť sekciu ↗'):(result.project?'Open project ↗':'View section ↗');
      button.addEventListener('click',()=>{dialog.close();if(result.project)showProject(result.project);else document.getElementById(result.section).scrollIntoView({behavior:document.documentElement.classList.contains('motion-off')?'instant':'smooth'});});row.append(button);
    }
    log.append(row);while(log.children.length>30)log.firstElementChild.remove();row.scrollIntoView({block:'nearest',behavior:'instant'});
  }
  function ask(text){if(!text.trim())return;append(text.trim().slice(0,300),'visitor');const result=answer(text,lang.value);append(result.text,'guide',result);input.value='';}
  document.querySelector('#guide-launcher').addEventListener('click',()=>{dialog.showModal();input.focus();});
  document.querySelector('#guide-form').addEventListener('submit',e=>{e.preventDefault();ask(input.value);});
  document.querySelectorAll('[data-question]').forEach(button=>button.addEventListener('click',()=>ask(button.dataset.question)));
  document.querySelector('#guide-clear').addEventListener('click',()=>{log.replaceChildren();input.value='';input.focus();});
})();
